"""深皮 product_kind → followup / 独立工单文案包（只换皮，不换引擎）。"""

from __future__ import annotations

from typing import Any, Callable


def crm_kind_overrides(
    kind: str,
    _std_archive_fields: Callable[..., list[dict[str, Any]]],
) -> dict[str, Any] | None:
    if kind == "legal":
        return {
            "user_label": "承办人",
            "admin_label": "律所主管（总管）",
            "archive_label": "案件",
            "archive_plural": "案件",
            "archive_fields": _std_archive_fields(
                "案件名称",
                "当事人",
                "案由/备注",
                "办案阶段",
                ["接待", "立案", "办理中", "结案", "搁置"],
                "案件分类",
                "可跟进",
            ),
            "ticket_label": "跟进单",
            "ticket_plural": "跟进",
            "verbs": {
                "apply": "登记跟进",
                "approve": "确认",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "archive_menu_admin": "案件档案",
            "archive_menu_user": "案件列表",
            "auth_eyebrow": "案件跟进",
            "auth_lead": "验证码登录；登记承办案件并提交跟进，跟进即时生效，可在完成后结案。",
            "auth_points": ["验证码登录", "案件档案", "跟进记录"],
            "register_hint": "注册后可登记案件并提交跟进",
            "notice_title": "办案须知",
            "notice_body": "请如实登记会见与办理进展；跟进提交后即时入档，办结后可查阅。",
            "notice_page_title": "律所公告",
            "notice_page_lead": "办案规范与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的跟进",
            "pending_label": "跟进确认",
            "records_label": "跟进记录",
            "remark_label": "跟进内容",
            "contact_channel_label": "联系方式",
            "contact_channel_options": ["面谈", "电话", "微信", "邮件", "其他"],
            "contact_channel_placeholder": "面谈/电话等",
            "next_follow_label": "下次跟进",
            "banners": [
                {"title": "案件档案", "lead": "按分类浏览案件，维护当事人与案由。"},
                {"title": "登记案件", "lead": "登录后可登记承办案件，即时可见。"},
                {"title": "办案跟进", "lead": "登记跟进即时生效，办结后可追溯。"},
                {"title": "律所公告", "lead": "办案规范与通知见公告栏。"},
                {"title": "我的跟进", "lead": "登录后查看跟进进度与记录。"},
            ],
        }
    if kind == "homevisit":
        return {
            "user_label": "学工",
            "admin_label": "学工主管（总管）",
            "archive_label": "谈话对象",
            "archive_plural": "谈话对象",
            "archive_fields": _std_archive_fields(
                "学生姓名",
                "班级/联系人",
                "家访事由/备注",
                "谈话阶段",
                ["待家访", "已家访", "需回访", "已闭环"],
                "关注分类",
                "可跟进",
            ),
            "ticket_label": "谈话记录",
            "ticket_plural": "谈话记录",
            "verbs": {
                "apply": "提交记录",
                "approve": "确认",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "archive_menu_admin": "谈话对象",
            "archive_menu_user": "对象列表",
            "auth_eyebrow": "家访谈心",
            "auth_lead": "验证码登录；维护谈话对象并提交家访/谈心记录，提交即时入档，可在完成后结案。",
            "auth_points": ["验证码登录", "谈话对象", "家访记录"],
            "register_hint": "注册后可提交家访与谈心谈话记录",
            "notice_title": "家访须知",
            "notice_body": "请如实登记家访或谈心内容；记录提交后即时入档，办结后可查阅。",
            "notice_page_title": "学工公告",
            "notice_page_lead": "家访规范与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的记录",
            "pending_label": "记录确认",
            "records_label": "谈话台账",
            "remark_label": "谈话内容",
            "contact_channel_label": "谈话形式",
            "contact_channel_options": ["上门家访", "电话", "到校约谈", "线上", "其他"],
            "contact_channel_placeholder": "上门/电话等",
            "next_follow_label": "下次回访",
            "banners": [
                {"title": "谈话对象", "lead": "按班级浏览重点学生，维护联系人与事由。"},
                {"title": "登记对象", "lead": "登录后可维护谈话对象档案。"},
                {"title": "家访记录", "lead": "提交家访或谈心记录，办结可追溯。"},
                {"title": "学工公告", "lead": "家访规范与通知见公告栏。"},
                {"title": "我的记录", "lead": "登录后查看记录进度。"},
            ],
        }
    if kind == "coop":
        return {
            "user_label": "联络员",
            "admin_label": "合作主管（总管）",
            "archive_label": "合作单位",
            "archive_plural": "合作单位",
            "archive_fields": _std_archive_fields(
                "单位名称",
                "对接人",
                "合作意向/备注",
                "合作阶段",
                ["接触", "意向", "签约", "履约", "搁置"],
                "单位分级",
                "可跟进",
            ),
            "ticket_label": "跟进单",
            "ticket_plural": "跟进",
            "verbs": {
                "apply": "提交跟进",
                "approve": "确认",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "archive_menu_admin": "合作单位库",
            "archive_menu_user": "单位列表",
            "auth_eyebrow": "校企合作",
            "auth_lead": "验证码登录；维护合作单位库并提交跟进，跟进即时生效，可在完成后结案。",
            "auth_points": ["验证码登录", "合作单位库", "跟进记录"],
            "register_hint": "注册后可维护合作单位并提交跟进",
            "notice_title": "合作须知",
            "notice_body": "请如实登记对接进展；跟进提交后即时入档，办结后可查阅。",
            "notice_page_title": "合作公告",
            "notice_page_lead": "校企合作规范与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的跟进",
            "pending_label": "跟进确认",
            "records_label": "跟进记录",
            "remark_label": "跟进内容",
            "contact_channel_label": "联系渠道",
            "contact_channel_options": ["到访", "电话", "邮件", "会议", "其他"],
            "contact_channel_placeholder": "到访/电话等",
            "next_follow_label": "下次跟进",
            "banners": [
                {"title": "合作单位库", "lead": "按分级浏览合作单位，维护对接人与意向。"},
                {"title": "登记单位", "lead": "登录后可登记合作单位，即时可见。"},
                {"title": "合作跟进", "lead": "提交跟进即时生效，办结后可追溯。"},
                {"title": "合作公告", "lead": "对接规范与通知见公告栏。"},
                {"title": "我的跟进", "lead": "登录后查看跟进进度。"},
            ],
        }
    return None
