"""E-R 中文词表（表名/列名/后缀规则）。"""

from __future__ import annotations

# —— 中文：领域名从表 domain.schema.json 取；这里只兜底骨架表 + 公共列词根 ——

# 各域 schema.sql 都会有、但不进 entities 的表（完整表名优先于拆段组词）
_INFRA_TABLE_ZH: dict[str, str] = {
    "sys_user": "用户",
    "sys_notice": "公告",
    "sys_message": "消息",
    "sys_guestbook": "留言",
    "sys_config": "配置",
    "category": "分类",
    "archive_log": "监测记录",
    "user_browse_history": "浏览足迹",
    "user_ledger": "账户流水",
    "reservation": "预约",
    "orders": "订单",
    "resource_slot": "时段名额",
}

# 表名拆段组词（biz_order → 业务+订单）；完整表名见 _INFRA_TABLE_ZH
_TABLE_PART_ZH: dict[str, str] = {
    "user": "用户",
    "sys": "系统",
    "ledger": "账本",
    "order": "订单",
    "biz": "业务",
    "shop": "店铺",
    "food": "餐饮",
    "hotel": "客房",
    "reservation": "预约",
    "ticket": "单据",
    "progress": "进度",
    "attach": "附件",
    "log": "日志",
    "lookup": "字典",
    "favorite": "收藏",
    "slot": "时段",
    "resource": "资源",
}

# 原子列名（可由后缀规则推出的不要再写一遍，见 _col_zh）
_COMMON_COL_ZH: dict[str, str] = {
    "id": "编号",
    "username": "用户名",
    "password": "密码",
    "role": "角色",
    "nickname": "昵称",
    "phone": "手机",
    "enabled": "启用",
    "status": "状态",
    "name": "名称",
    "title": "标题",
    "content": "内容",
    "body": "正文",
    "remark": "说明",
    "qty": "数量",
    "stock": "库存",
    "action": "动作",
    "operator": "操作人",
    "code": "编码",
    "location": "地点",
    "capacity": "容量",
    "price": "价格",
    "rating": "评分",
    "booked": "已约",
    "cfg_key": "配置键",
    "cfg_value": "配置值",
    "super_admin": "总管",
    "profile_editable": "可改资料",
    "profile_json": "资料",
    "kind": "类型",
    "delta": "变动额",
    "reason": "事由",
    "points": "积分",
    "member_tier": "会员等级",
    "points_earned": "获积分",
}

# 去掉后缀后的词根（*_at / *_url / *_yuan / *_msg / *_code / *_after …）
_STEM_ZH: dict[str, str] = {
    "created": "创建",
    "updated": "更新",
    "deleted": "删除",
    "apply": "申请",
    "approve": "受理",
    "due": "到期",
    "return": "完结",
    "reminded": "催办",
    "remind": "催办",
    "rated": "评价",
    "rating": "评价",
    "checked_in": "签到",
    "start": "开始",
    "end": "结束",
    "read": "已读",
    "period_start": "开始",
    "period_end": "结束",
    "apply_deadline": "报名截止",
    "avatar": "头像",
    "attach": "附件",
    "profile": "资料",
    "fine": "费用",
    "price": "价格",
    "line": "小计",
    "checkin": "签到",
    "mutex": "互斥",
    "publisher": "发布人",
    "assignee": "处理人",
    "ref": "关联",
    "parent": "上级",
    "balance": "余额",
    "spend_total": "累计消费",
    "discount": "优惠",
    "pay_balance": "余额支付",
    "member": "会员",
    "ship": "物流",
    "pickup": "取餐",
    "flavor": "口味",
    "address": "地址",
}

# (suffix, 默认中文, 有词根时的格式；{stem} 占位)
_COL_SUFFIX_RULES: tuple[tuple[str, str, str], ...] = (
    ("_username", "用户账号", "{stem}账号"),
    ("_name", "名称", "{stem}"),
    ("_at", "时间", "{stem}时间"),
    ("_url", "链接", "{stem}链接"),
    ("_yuan", "金额", "{stem}"),
    ("_msg", "说明", "{stem}说明"),
    ("_code", "编码", "{stem}码"),
    ("_json", "资料", "{stem}"),
    ("_type", "类型", "{stem}类型"),
    ("_after", "变动后", "变动后{stem}"),
    ("_note", "备注", "{stem}备注"),
    ("_method", "方式", "{stem}方式"),
    ("_status", "状态", "{stem}状态"),
    ("_no", "单号", "{stem}单号"),
)
