"""E-R 中文词表（表名/列名/后缀规则）。"""

from __future__ import annotations

# —— 中文：领域名从表 domain.schema.json 取；这里只兜底骨架表 + 公共列词根 ——

# 各域 schema.sql 都会有、但不进 entities 的表（完整表名优先于拆段组词）
_INFRA_TABLE_ZH: dict[str, str] = {
    "sys_user": "用户",
    "sys_notice": "公告",
    "sys_message": "消息",
    "sys_guestbook": "留言",
    "sys_dm_message": "私信",
    "exam_subject": "考试科目",
    "exam_question": "考题",
    "exam_paper": "试卷",
    "exam_paper_question": "试卷题目",
    "exam_attempt": "答卷",
    "exam_answer": "作答",
    "exam_wrongbook": "错题本",
    "survey_form": "问卷",
    "survey_question": "问卷题",
    "survey_response": "答卷",
    "survey_answer": "问卷作答",
    "vote_campaign": "评选活动",
    "vote_candidate": "候选人",
    "vote_ballot": "选票",
    "doc_item": "资料",
    "download_log": "下载记录",
    "trip_route": "行程",
    "tour_line": "线路",
    "tour_signup": "线路报名",
    "tour_signup_log": "报名日志",
    "carpool_intent": "同行意向",
    "carpool_intent_log": "意向日志",
    "tb_service": "服务事项",
    "tb_account": "时长账户",
    "tb_ledger": "时长流水",
    "tb_redeem": "核销申请",
    "tb_redeem_log": "核销日志",
    "cinema_show": "场次",
    "cinema_seat": "座位",
    "category": "分类",
    "archive_log": "监测记录",
    "user_browse_history": "浏览足迹",
    "user_ledger": "账户流水",
    "reservation": "预约",
    "orders": "订单",
    "resource_slot": "时段名额",
}

# 表名拆段组词（biz_order → 业务+订单）；完整表名见 _INFRA_TABLE_ZH
_TABLE_PART_ZH: dict[str, str] = {
    "user": "用户",
    "sys": "系统",
    "ledger": "账本",
    "order": "订单",
    "biz": "业务",
    "shop": "店铺",
    "food": "餐饮",
    "hotel": "客房",
    "reservation": "预约",
    "ticket": "单据",
    "progress": "进度",
    "attach": "附件",
    "log": "日志",
    "lookup": "字典",
    "favorite": "收藏",
    "slot": "时段",
    "resource": "资源",
}

# 原子列名（可由后缀规则推出的不要再写一遍，见 _col_zh）
_COMMON_COL_ZH: dict[str, str] = {
    "id": "编号",
    "username": "用户名",
    "password": "密码",
    "role": "角色",
    "nickname": "昵称",
    "phone": "手机",
    "enabled": "启用",
    "status": "状态",
    "name": "名称",
    "title": "标题",
    "content": "内容",
    "body": "正文",
    "remark": "说明",
    "subtitle": "副标题",
    "detail": "说明",
    "planner": "计调",
    "highlight_note": "行程亮点",
    "author": "作者",
    "isbn": "ISBN",
    "brand_model": "品牌/型号",
    "spec_model": "规格/型号",
    "asset_no": "资产编号",
    "building_name": "楼栋",
    "publisher_name": "发布人",
    "route_note": "地点备注",
    "driver_name": "司机",
    "vehicle_note": "车型说明",
    "contractor": "责任单位",
    "work_req": "施工要求",
    "lab_name": "所属实验室",
    "model_note": "型号规格",
    "layout_note": "布局说明",
    "room_note": "房型说明",
    "price_yuan": "价格",
    "fee_yuan": "费用",
    "location_note": "位置说明",
    "title_note": "职称/说明",
    "duration_note": "时长说明",
    "cast_info": "导演/主演",
    "play_url": "播放链接",
    "body_html": "正文",
    "artist": "歌手/专辑",
    "patient_name": "预约人",
    "visit_type": "业务类型",
    "symptom_note": "说明",
    "preferred_stylist": "偏好技师",
    "plate_no": "车牌号",
    "party_size": "人数",
    "guest_name": "入住人",
    "guest_count": "入住人数",
    "subject": "主题",
    "queue_no": "排队号",
    "entry_at": "入场时间",
    "sku": "货号",
    "contact_name": "联系人",
    "contact_note": "电话/备注",
    "handler_name": "随访员",
    "case_summary": "病种/健康摘要",
    "scope_note": "适用说明",
    "apply_note": "申请须知备注",
    "own_unit": "归口单位",
    "quota_note": "名额/条件备注",
    "building_lead": "楼宇/负责人",
    "safety_note": "安全等级备注",
    "hire_dept": "用人部门",
    "salary_note": "薪资/任职要求",
    "teacher_name": "授课教师",
    "course_code": "课号/学分",
    "mentor_name": "企业导师",
    "org_note": "单位/岗位说明",
    "station_name": "站点",
    "pickup_code": "取件码/柜号",
    "lecturer_name": "任课教师",
    "course_note": "开课说明",
    "college_name": "所属院系",
    "research_note": "研究方向/说明",
    "skill_note": "技能/缺人说明",
    "zone_place": "楼栋/位置",
    "receive_note": "接待说明",
    "estate_area": "小区/区域",
    "house_type_note": "户型说明",
    "item_spec": "规格说明",
    "guide_unit": "指导单位",
    "matter_note": "事项说明",
    "declare_note": "申报说明",
    "material_brief": "材料说明",
    "party_org": "党组织",
    "approve_note": "审批说明",
    "course_unit": "开课单位",
    "publish_unit": "发布单位",
    "host_unit": "主办单位",
    "rule_note": "规则说明",
    "summary_note": "摘要说明",
    "keeper_dept": "保管部门",
    "seal_scope": "用印范围",
    "issue_dept": "开具部门",
    "purpose_note": "用途说明",
    "apply_unit": "申报单位",
    "post_place": "张贴位置",
    "accept_dept": "受理部门",
    "material_note": "材料要求",
    "own_dept": "归口部门",
    "fill_note": "填报说明",
    "budget_note": "预算说明",
    "organizer": "组织方",
    "service_note": "说明",
    "hall_note": "影厅名称",
    "seat_rows": "座位排数",
    "seat_cols": "每排座位数",
    "start_at": "开始时间",
    "dept_name": "责任部门",
    "note_hint": "说明",
    "qty": "数量",
    "stock": "库存",
    "action": "动作",
    "operator": "操作人",
    "code": "编码",
    "location": "地点",
    "capacity": "容量",
    "price": "价格",
    "rating": "评分",
    "booked": "已约",
    "cfg_key": "配置键",
    "cfg_value": "配置值",
    "super_admin": "总管",
    "profile_editable": "可改资料",
    "profile_json": "资料",
    "staff_post": "岗位",
    "staff_kind": "岗位类型",
    "kind": "类型",
    "delta": "变动额",
    "reason": "事由",
    "points": "积分",
    "member_tier": "会员等级",
    "points_earned": "获积分",
}

# 去掉后缀后的词根（*_at / *_url / *_yuan / *_msg / *_code / *_after …）
_STEM_ZH: dict[str, str] = {
    "created": "创建",
    "updated": "更新",
    "deleted": "删除",
    "apply": "申请",
    "approve": "受理",
    "due": "到期",
    "return": "完结",
    "reminded": "催办",
    "remind": "催办",
    "rated": "评价",
    "rating": "评价",
    "checked_in": "签到",
    "start": "开始",
    "end": "结束",
    "read": "已读",
    "period_start": "开始",
    "period_end": "结束",
    "apply_deadline": "报名截止",
    "avatar": "头像",
    "attach": "附件",
    "profile": "资料",
    "fine": "费用",
    "price": "价格",
    "line": "小计",
    "checkin": "签到",
    "mutex": "互斥",
    "publisher": "发布人",
    "assignee": "处理人",
    "ref": "关联",
    "parent": "上级",
    "balance": "余额",
    "spend_total": "累计消费",
    "discount": "优惠",
    "pay_balance": "余额支付",
    "member": "会员",
    "ship": "物流",
    "pickup": "取餐",
    "flavor": "口味",
    "address": "地址",
}

# (suffix, 默认中文, 有词根时的格式；{stem} 占位)
_COL_SUFFIX_RULES: tuple[tuple[str, str, str], ...] = (
    ("_username", "用户账号", "{stem}账号"),
    ("_name", "名称", "{stem}"),
    ("_at", "时间", "{stem}时间"),
    ("_url", "链接", "{stem}链接"),
    ("_yuan", "金额", "{stem}"),
    ("_msg", "说明", "{stem}说明"),
    ("_code", "编码", "{stem}码"),
    ("_json", "资料", "{stem}"),
    ("_type", "类型", "{stem}类型"),
    ("_after", "变动后", "变动后{stem}"),
    ("_note", "备注", "{stem}备注"),
    ("_method", "方式", "{stem}方式"),
    ("_status", "状态", "{stem}状态"),
    ("_no", "单号", "{stem}单号"),
)
