"""互选 FOLLOWUP_PRESETS（P-09～P-11 · C-05）。"""

from __future__ import annotations

from typing import Any, Callable


def build_mutual_followup_presets(
    _std_archive_fields: Callable[..., list[dict[str, Any]]],
) -> dict[str, dict[str, Any]]:
    return {
"DOM-MUTUAL-TUTOR": {
    "doc": "导师双选：导师档案 + 志愿 + 对方确认（管理可调剂）。",
    "user_label": "学生",
    "admin_label": "教务主管（总管）",
    "subadmin_label": "导师秘书",
    "archive_key": "tutor",
    "archive_label": "导师",
    "archive_plural": "导师",
    "archive_fields": [
        {"key": "title", "label": "导师名称", "type": "string"},
        {"key": "author", "label": "所属院系", "type": "string"},
        {"key": "isbn", "label": "研究方向/说明", "type": "string"},
        {"key": "category", "label": "类别", "type": "select"},
        {"key": "stock", "label": "可带名额", "type": "number"},
        {"key": "ownerUsername", "label": "确认账号", "type": "string"},
    ],
    "stock_display": "count",
    "ticket_key": "tutor_wish",
    "ticket_label": "导师志愿",
    "ticket_plural": "导师志愿",
    "verbs": {
        "apply": "提交志愿",
        "approve": "调剂确认",
        "reject": "调剂驳回",
        "return": "撤销志愿",
        "remind": "催确认",
    },
    "states": {
        "pending": "待对方确认",
        "approved": "已互选",
        "rejected": "已婉拒",
        "returned": "已撤销",
        "overdue": "已失效",
    },
    "archive_menu_admin": "导师档案",
    "archive_menu_user": "导师目录",
    "auth_eyebrow": "导师双选",
    "auth_lead": "验证码登录；浏览导师提交志愿，由确认人接受或婉拒；管理端可调剂。",
    "auth_points": ["验证码登录", "导师目录", "志愿互选确认"],
    "register_hint": "注册后可提交志愿",
    "notice_title": "导师双选须知",
    "notice_body": "请如实填写志愿说明；确认后占用名额。智能推荐与多轮排序不在本期。",
    "notice_page_title": "互选公告",
    "notice_page_lead": "双选安排与须知，点击条目阅读全文。",
    "my_tickets_label": "我的志愿",
    "pending_label": "调剂确认",
    "records_label": "志愿记录",
    "remark_label": "志愿说明",
    "peer_inbox_label": "待我确认",
    "auto_approve": False,
    "approve_ends_flow": True,
    "peer_accept": True,
    "contact_channel_label": "志愿类型",
    "contact_channel_options": ["第一志愿", "第二志愿", "调剂志愿", "其他"],
    "contact_channel_placeholder": "第一/第二志愿等",
    "next_follow_label": "期望确认日",
    "banners": [
        {"title": "导师目录", "lead": "浏览可申报对象与名额。"},
        {"title": "提交志愿", "lead": "选择对象提交志愿，等待确认。"},
        {"title": "待我确认", "lead": "他人向你发起的志愿在此确认或婉拒。"},
        {"title": "互选公告", "lead": "节点与须知见公告栏。"},
        {"title": "我的志愿", "lead": "跟踪确认与调剂结果。"},
    ],
},

"DOM-MUTUAL-TOPIC": {
    "doc": "选题双选：选题档案 + 志愿 + 对方确认（管理可调剂）。",
    "user_label": "学生",
    "admin_label": "教务主管（总管）",
    "subadmin_label": "选题秘书",
    "archive_key": "thesis_topic",
    "archive_label": "选题",
    "archive_plural": "选题",
    "archive_fields": [
        {"key": "title", "label": "选题名称", "type": "string"},
        {"key": "author", "label": "所属院系", "type": "string"},
        {"key": "isbn", "label": "研究方向/说明", "type": "string"},
        {"key": "category", "label": "类别", "type": "select"},
        {"key": "stock", "label": "可带名额", "type": "number"},
        {"key": "ownerUsername", "label": "确认账号", "type": "string"},
    ],
    "stock_display": "count",
    "ticket_key": "topic_wish",
    "ticket_label": "选题志愿",
    "ticket_plural": "选题志愿",
    "verbs": {
        "apply": "提交志愿",
        "approve": "调剂确认",
        "reject": "调剂驳回",
        "return": "撤销志愿",
        "remind": "催确认",
    },
    "states": {
        "pending": "待对方确认",
        "approved": "已互选",
        "rejected": "已婉拒",
        "returned": "已撤销",
        "overdue": "已失效",
    },
    "archive_menu_admin": "选题档案",
    "archive_menu_user": "选题目录",
    "auth_eyebrow": "选题双选",
    "auth_lead": "验证码登录；浏览选题提交志愿，由确认人接受或婉拒；管理端可调剂。",
    "auth_points": ["验证码登录", "选题目录", "志愿互选确认"],
    "register_hint": "注册后可提交志愿",
    "notice_title": "选题双选须知",
    "notice_body": "请如实填写志愿说明；确认后占用名额。智能推荐与多轮排序不在本期。",
    "notice_page_title": "互选公告",
    "notice_page_lead": "双选安排与须知，点击条目阅读全文。",
    "my_tickets_label": "我的志愿",
    "pending_label": "调剂确认",
    "records_label": "志愿记录",
    "remark_label": "志愿说明",
    "peer_inbox_label": "待我确认",
    "auto_approve": False,
    "approve_ends_flow": True,
    "peer_accept": True,
    "contact_channel_label": "志愿类型",
    "contact_channel_options": ["第一志愿", "第二志愿", "调剂志愿", "其他"],
    "contact_channel_placeholder": "第一/第二志愿等",
    "next_follow_label": "期望确认日",
    "banners": [
        {"title": "选题目录", "lead": "浏览可申报对象与名额。"},
        {"title": "提交志愿", "lead": "选择对象提交志愿，等待确认。"},
        {"title": "待我确认", "lead": "他人向你发起的志愿在此确认或婉拒。"},
        {"title": "互选公告", "lead": "节点与须知见公告栏。"},
        {"title": "我的志愿", "lead": "跟踪确认与调剂结果。"},
    ],
},

"DOM-MUTUAL-TEAM": {
    "doc": "组队匹配：组队资料档案 + 志愿 + 对方确认（管理可调剂）。",
    "user_label": "学生",
    "admin_label": "教务主管（总管）",
    "subadmin_label": "组队协调员",
    "archive_key": "team_profile",
    "archive_label": "组队资料",
    "archive_plural": "组队资料",
    "archive_fields": [
        {"key": "title", "label": "组队资料名称", "type": "string"},
        {"key": "author", "label": "所属院系", "type": "string"},
        {"key": "isbn", "label": "研究方向/说明", "type": "string"},
        {"key": "category", "label": "类别", "type": "select"},
        {"key": "stock", "label": "可带名额", "type": "number"},
        {"key": "ownerUsername", "label": "确认账号", "type": "string"},
    ],
    "stock_display": "count",
    "ticket_key": "team_wish",
    "ticket_label": "组队意向",
    "ticket_plural": "组队意向",
    "verbs": {
        "apply": "提交志愿",
        "approve": "调剂确认",
        "reject": "调剂驳回",
        "return": "撤销志愿",
        "remind": "催确认",
    },
    "states": {
        "pending": "待对方确认",
        "approved": "已互选",
        "rejected": "已婉拒",
        "returned": "已撤销",
        "overdue": "已失效",
    },
    "archive_menu_admin": "组队资料档案",
    "archive_menu_user": "组队资料目录",
    "auth_eyebrow": "组队匹配",
    "auth_lead": "验证码登录；浏览组队资料提交志愿，由确认人接受或婉拒；管理端可调剂。",
    "auth_points": ["验证码登录", "组队资料目录", "志愿互选确认"],
    "register_hint": "注册后可提交志愿",
    "notice_title": "组队匹配须知",
    "notice_body": "请如实填写志愿说明；确认后占用名额。智能推荐与多轮排序不在本期。",
    "notice_page_title": "互选公告",
    "notice_page_lead": "双选安排与须知，点击条目阅读全文。",
    "my_tickets_label": "我的志愿",
    "pending_label": "调剂确认",
    "records_label": "志愿记录",
    "remark_label": "志愿说明",
    "peer_inbox_label": "待我确认",
    "auto_approve": False,
    "approve_ends_flow": True,
    "peer_accept": True,
    "contact_channel_label": "志愿类型",
    "contact_channel_options": ["第一志愿", "第二志愿", "调剂志愿", "其他"],
    "contact_channel_placeholder": "第一/第二志愿等",
    "next_follow_label": "期望确认日",
    "banners": [
        {"title": "组队资料目录", "lead": "浏览可申报对象与名额。"},
        {"title": "提交志愿", "lead": "选择对象提交志愿，等待确认。"},
        {"title": "待我确认", "lead": "他人向你发起的志愿在此确认或婉拒。"},
        {"title": "互选公告", "lead": "节点与须知见公告栏。"},
        {"title": "我的志愿", "lead": "跟踪确认与调剂结果。"},
    ],
},
    }
