"""OA 申请域 FOLLOWUP_PRESETS（P-01～P-08）。各选题方向字段/动词分立，勿八域同文案。"""

from __future__ import annotations

from typing import Any, Callable

# 申请→审→完结/销结；无借阅逾期态（勿挂 dead overdue）
_OA_STATES_DONE = {
    "pending": "待审",
    "approved": "已通过",
    "rejected": "已驳回",
    "returned": "已完结",
}

_OA_STATES_TRIP = {
    "pending": "待审",
    "approved": "已通过",
    "rejected": "已驳回",
    "returned": "已销结",
}


def build_oa_followup_presets(
    _std_archive_fields: Callable[..., list[dict[str, Any]]],
) -> dict[str, dict[str, Any]]:
    out = {
        "DOM-SEAL": {
            "doc": "用章申请：印章事项 + 用章申请。",
            "user_label": "申请人",
            "admin_label": "行政主管（总管）",
            "subadmin_label": "用章管理员",
            "archive_key": "seal_item",
            "archive_label": "印章事项",
            "archive_plural": "印章事项",
            "archive_fields": _std_archive_fields(
                "用章事项",
                "保管部门",
                "用印范围",
                "开放状态",
                ["开放", "暂停", "关闭"],
                "印章类型",
                "可申请",
            ),
            "ticket_key": "seal_apply",
            "ticket_label": "用章申请",
            "ticket_plural": "用章申请",
            "verbs": {
                "apply": "提交用章",
                "approve": "通过",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "states": dict(_OA_STATES_DONE),
            "archive_menu_admin": "印章事项",
            "archive_menu_user": "印章事项说明",
            "auth_eyebrow": "用章申请",
            "auth_lead": "验证码登录；选择印章事项并提交用章，管理员审批后完结。",
            "auth_points": ["验证码登录", "印章事项", "提交用章与审批"],
            "register_hint": "注册后可提交用章",
            "notice_title": "用章申请须知",
            "notice_body": "请如实填写用章事由与文件名称；审批通过后方可办理用印。本期无硬件盖章对接。",
            "notice_page_title": "办理公告",
            "notice_page_lead": "用章须知与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的申请",
            "pending_label": "待审申请",
            "records_label": "申请记录",
            "remark_label": "用章事由",
            "auto_approve": False,
            "approve_ends_flow": True,
            "contact_channel_label": "用印方式",
            "contact_channel_options": ["现场用印", "外带用印", "窗口补录", "其他"],
            "contact_channel_placeholder": "现场/外带等",
            "next_follow_label": "期望用印日",
            "banners": [
                {"title": "印章事项说明", "lead": "查阅可申请印章与用印范围。"},
                {"title": "提交用章", "lead": "选择事项填写事由，等待审批。"},
                {"title": "办理公告", "lead": "须知与节点见公告栏。"},
                {"title": "我的申请", "lead": "跟踪审批与完结进度。"},
                {"title": "分类检索", "lead": "按印章类型筛选。"},
            ],
        },
        "DOM-FLEET": {
            "doc": "用车申请：车辆 + 用车申请。",
            "user_label": "用车人",
            "admin_label": "车队主管（总管）",
            "subadmin_label": "调度员",
            "archive_key": "fleet_vehicle",
            "archive_label": "车辆",
            "archive_plural": "车辆",
            "archive_fields": _std_archive_fields(
                "车牌号",
                "司机",
                "车型说明",
                "调度状态",
                ["开放", "暂停", "关闭"],
                "车型分类",
                "可申请",
            ),
            "ticket_key": "fleet_apply",
            "ticket_label": "用车申请",
            "ticket_plural": "用车申请",
            "verbs": {
                "apply": "提交用车",
                "approve": "通过",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "states": dict(_OA_STATES_DONE),
            "archive_menu_admin": "车辆",
            "archive_menu_user": "车辆说明",
            "auth_eyebrow": "用车申请",
            "auth_lead": "验证码登录；选择车辆并提交用车，管理员审批后完结。",
            "auth_points": ["验证码登录", "车辆说明", "提交用车与审批"],
            "register_hint": "注册后可提交用车",
            "notice_title": "用车申请须知",
            "notice_body": "请如实填写用车事由、人数与目的地；审批通过后方可出车。本期无 GPS/真派单对接。",
            "notice_page_title": "办理公告",
            "notice_page_lead": "用车须知与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的申请",
            "pending_label": "待审申请",
            "records_label": "申请记录",
            "remark_label": "用车事由",
            "auto_approve": False,
            "approve_ends_flow": True,
            "contact_channel_label": "用车类型",
            "contact_channel_options": ["市内公务", "接待用车", "物资运送", "其他"],
            "contact_channel_placeholder": "市内/接待等",
            "next_follow_label": "用车日期",
            "pick_date_range": False,
            "banners": [
                {"title": "车辆说明", "lead": "查阅车牌、司机与车型。"},
                {"title": "提交用车", "lead": "选择车辆填写事由，等待调度审批。"},
                {"title": "办理公告", "lead": "须知与节点见公告栏。"},
                {"title": "我的申请", "lead": "跟踪审批进度。"},
                {"title": "分类检索", "lead": "按车型筛选。"},
            ],
        },
        "DOM-CERT": {
            "doc": "开具证明：证明类型 + 开具申请。",
            "user_label": "申请人",
            "admin_label": "综合主管（总管）",
            "subadmin_label": "证明专员",
            "archive_key": "cert_type",
            "archive_label": "证明类型",
            "archive_plural": "证明类型",
            "archive_fields": _std_archive_fields(
                "证明名称",
                "开具部门",
                "用途说明",
                "开放状态",
                ["开放", "暂停", "关闭"],
                "证明类别",
                "可申请",
            ),
            "ticket_key": "cert_apply",
            "ticket_label": "开具申请",
            "ticket_plural": "开具申请",
            "verbs": {
                "apply": "申请开具",
                "approve": "通过",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "states": dict(_OA_STATES_DONE),
            "archive_menu_admin": "证明类型",
            "archive_menu_user": "证明类型说明",
            "auth_eyebrow": "开具证明",
            "auth_lead": "验证码登录；选择证明类型并申请开具，管理员审批后完结。",
            "auth_points": ["验证码登录", "证明类型", "申请开具与审批"],
            "register_hint": "注册后可申请开具",
            "notice_title": "开具申请须知",
            "notice_body": "请如实填写用途与领取方式；审批通过后按须知领取。本期无电子签章平台对接。",
            "notice_page_title": "办理公告",
            "notice_page_lead": "开具须知与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的申请",
            "pending_label": "待审申请",
            "records_label": "申请记录",
            "remark_label": "开具用途",
            "auto_approve": False,
            "approve_ends_flow": True,
            "contact_channel_label": "领取方式",
            "contact_channel_options": ["窗口领取", "邮寄", "电子版", "其他"],
            "contact_channel_placeholder": "窗口/邮寄等",
            "next_follow_label": "期望领取日",
            "banners": [
                {"title": "证明类型说明", "lead": "查阅在读/在职/成绩单等类型。"},
                {"title": "申请开具", "lead": "选择类型填写用途，等待审批。"},
                {"title": "办理公告", "lead": "须知与节点见公告栏。"},
                {"title": "我的申请", "lead": "跟踪开具进度。"},
                {"title": "分类检索", "lead": "按证明类别筛选。"},
            ],
        },
        "DOM-PROMO": {
            "doc": "宣传审批：宣传事项 + 宣传审批。",
            "user_label": "申报人",
            "admin_label": "宣传主管（总管）",
            "subadmin_label": "宣传员",
            "archive_key": "promo_matter",
            "archive_label": "宣传事项",
            "archive_plural": "宣传事项",
            "archive_fields": _std_archive_fields(
                "宣传主题",
                "申报单位",
                "张贴位置",
                "开放状态",
                ["开放", "暂停", "关闭"],
                "宣传形式",
                "可申请",
            ),
            "ticket_key": "promo_apply",
            "ticket_label": "宣传审批",
            "ticket_plural": "宣传审批",
            "verbs": {
                "apply": "提交方案",
                "approve": "通过",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "states": dict(_OA_STATES_DONE),
            "archive_menu_admin": "宣传事项",
            "archive_menu_user": "宣传事项说明",
            "auth_eyebrow": "宣传审批",
            "auth_lead": "验证码登录；选择宣传事项并提交方案，管理员审批后完结。",
            "auth_points": ["验证码登录", "宣传事项", "提交方案与审批"],
            "register_hint": "注册后可提交方案",
            "notice_title": "宣传审批须知",
            "notice_body": "请如实填写张贴内容与位置；未审批不得张贴。本期无户外硬件联动。",
            "notice_page_title": "办理公告",
            "notice_page_lead": "宣传须知与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的申请",
            "pending_label": "待审申请",
            "records_label": "申请记录",
            "remark_label": "方案说明",
            "auto_approve": False,
            "approve_ends_flow": True,
            "contact_channel_label": "宣传形式",
            "contact_channel_options": ["横幅", "海报", "展板", "其他"],
            "contact_channel_placeholder": "横幅/海报等",
            "next_follow_label": "计划张贴日",
            "banners": [
                {"title": "宣传事项说明", "lead": "查阅可申报的宣传主题与位置。"},
                {"title": "提交方案", "lead": "填写内容与张贴说明，等待审批。"},
                {"title": "办理公告", "lead": "须知与节点见公告栏。"},
                {"title": "我的申请", "lead": "跟踪审批进度。"},
                {"title": "分类检索", "lead": "按宣传形式筛选。"},
            ],
        },
        "DOM-FITOUT": {
            "doc": "装修备案：施工区域 + 装修备案。",
            "user_label": "申报人",
            "admin_label": "工程主管（总管）",
            "subadmin_label": "备案员",
            "archive_key": "fitout_site",
            "archive_label": "施工区域",
            "archive_plural": "施工区域",
            "archive_fields": _std_archive_fields(
                "施工区域",
                "责任单位",
                "施工要求",
                "开放状态",
                ["开放", "暂停", "关闭"],
                "工程类型",
                "可申请",
            ),
            "ticket_key": "fitout_apply",
            "ticket_label": "装修备案",
            "ticket_plural": "装修备案",
            "verbs": {
                "apply": "提交备案",
                "approve": "通过",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "states": dict(_OA_STATES_DONE),
            "archive_menu_admin": "施工区域",
            "archive_menu_user": "施工区域说明",
            "auth_eyebrow": "装修备案",
            "auth_lead": "验证码登录；选择施工区域并提交备案，管理员审批后完结。",
            "auth_points": ["验证码登录", "施工区域", "提交备案与审批"],
            "register_hint": "注册后可提交备案",
            "notice_title": "装修备案须知",
            "notice_body": "请如实填写施工内容、工期与安全措施；备案通过后方可进场。本期无物联网门禁对接。",
            "notice_page_title": "办理公告",
            "notice_page_lead": "备案须知与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的申请",
            "pending_label": "待审申请",
            "records_label": "申请记录",
            "remark_label": "施工说明",
            "auto_approve": False,
            "approve_ends_flow": True,
            "contact_channel_label": "施工时段",
            "contact_channel_options": ["白天施工", "夜间施工", "周末施工", "其他"],
            "contact_channel_placeholder": "白天/夜间等",
            "next_follow_label": "计划进场日",
            "banners": [
                {"title": "施工区域说明", "lead": "查阅可备案区域与工期要求。"},
                {"title": "提交备案", "lead": "填写施工说明，等待备案审批。"},
                {"title": "办理公告", "lead": "须知与节点见公告栏。"},
                {"title": "我的申请", "lead": "跟踪备案进度。"},
                {"title": "分类检索", "lead": "按工程类型筛选。"},
            ],
        },
        "DOM-ACAD": {
            "doc": "学籍异动：异动事项 + 异动申请。",
            "user_label": "学生",
            "admin_label": "教务主管（总管）",
            "subadmin_label": "教务员",
            "archive_key": "acad_matter",
            "archive_label": "异动事项",
            "archive_plural": "异动事项",
            "archive_fields": _std_archive_fields(
                "异动事项",
                "受理部门",
                "材料要求",
                "开放状态",
                ["开放", "暂停", "关闭"],
                "异动类型",
                "可申请",
            ),
            "ticket_key": "acad_apply",
            "ticket_label": "异动申请",
            "ticket_plural": "异动申请",
            "verbs": {
                "apply": "提交申请",
                "approve": "通过",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "states": dict(_OA_STATES_DONE),
            "archive_menu_admin": "异动事项",
            "archive_menu_user": "异动事项说明",
            "auth_eyebrow": "学籍异动",
            "auth_lead": "学生验证码登录；选择异动事项并提交申请，教务审批后完结。",
            "auth_points": ["验证码登录", "异动事项", "提交申请与审批"],
            "register_hint": "注册后可提交学籍异动申请",
            "notice_title": "异动申请须知",
            "notice_body": "请如实填写异动事由并按材料要求准备附件说明；审批通过后按教务安排办理。",
            "notice_page_title": "办理公告",
            "notice_page_lead": "异动须知与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的申请",
            "pending_label": "待审申请",
            "records_label": "申请记录",
            "remark_label": "异动事由",
            "auto_approve": False,
            "approve_ends_flow": True,
            "contact_channel_label": "异动类型",
            "contact_channel_options": ["转专业", "缓考", "休学", "复学", "其他"],
            "contact_channel_placeholder": "转专业/缓考等",
            "next_follow_label": "期望办结日",
            "banners": [
                {"title": "异动事项说明", "lead": "查阅转专业、缓考、休学复学等事项。"},
                {"title": "提交申请", "lead": "选择事项填写事由，等待教务审批。"},
                {"title": "办理公告", "lead": "须知与节点见公告栏。"},
                {"title": "我的申请", "lead": "跟踪审批进度。"},
                {"title": "分类检索", "lead": "按异动类型筛选。"},
            ],
        },
        "DOM-TRIP": {
            "doc": "出差加班：事项类型 + 出差加班单。",
            "user_label": "申请人",
            "admin_label": "人事主管（总管）",
            "subadmin_label": "考勤员",
            "archive_key": "trip_matter",
            "archive_label": "事项类型",
            "archive_plural": "事项类型",
            "archive_fields": _std_archive_fields(
                "事项类型",
                "归口部门",
                "填报说明",
                "开放状态",
                ["开放", "暂停", "关闭"],
                "业务分类",
                "可申请",
            ),
            "ticket_key": "trip_apply",
            "ticket_label": "出差加班单",
            "ticket_plural": "出差加班单",
            "verbs": {
                "apply": "提交申请",
                "approve": "通过",
                "reject": "驳回",
                "return": "销结",
                "remind": "催办",
            },
            "states": dict(_OA_STATES_TRIP),
            "archive_menu_admin": "事项类型",
            "archive_menu_user": "事项类型说明",
            "auth_eyebrow": "出差加班",
            "auth_lead": "验证码登录；选择事项类型并提交申请，审批通过后销结。",
            "auth_points": ["验证码登录", "事项类型", "申请审批与销结"],
            "register_hint": "注册后可提交出差/加班申请",
            "notice_title": "出差加班单须知",
            "notice_body": "请填写事由与起止日期；审批通过后按时销结。本期无 GPS 轨迹考勤。",
            "notice_page_title": "办理公告",
            "notice_page_lead": "出差加班须知与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的申请",
            "pending_label": "待审申请",
            "records_label": "申请记录",
            "remark_label": "事由与行程",
            "auto_approve": False,
            "approve_ends_flow": True,
            "contact_channel_label": "申请类别",
            "contact_channel_options": ["市内公出", "出差", "加班", "其他"],
            "contact_channel_placeholder": "公出/出差/加班",
            "next_follow_label": "预计返回日",
            "pick_date_range": True,
            "banners": [
                {"title": "事项类型说明", "lead": "查阅公出、出差与加班类型。"},
                {"title": "提交申请", "lead": "填写事由与起止日期，等待审批。"},
                {"title": "办理公告", "lead": "须知与节点见公告栏。"},
                {"title": "我的申请", "lead": "跟踪审批与销结。"},
                {"title": "分类检索", "lead": "按业务分类筛选。"},
            ],
        },
        "DOM-EXPENSE": {
            "doc": "经费报销：经费项目 + 报销单（无银行直连）。",
            "user_label": "报销人",
            "admin_label": "财务主管（总管）",
            "subadmin_label": "报销审核员",
            "archive_key": "expense_project",
            "archive_label": "经费项目",
            "archive_plural": "经费项目",
            "archive_fields": _std_archive_fields(
                "经费项目",
                "归口部门",
                "预算说明",
                "开放状态",
                ["开放", "暂停", "关闭"],
                "费用类别",
                "可申请",
            ),
            "ticket_key": "expense_apply",
            "ticket_label": "报销单",
            "ticket_plural": "报销单",
            "verbs": {
                "apply": "提交报销",
                "approve": "通过",
                "reject": "驳回",
                "return": "完结",
                "remind": "催办",
            },
            "states": dict(_OA_STATES_DONE),
            "archive_menu_admin": "经费项目",
            "archive_menu_user": "经费项目说明",
            "auth_eyebrow": "经费报销",
            "auth_lead": "验证码登录；选择经费项目填写金额与说明，管理员审批后完结。",
            "auth_points": ["验证码登录", "经费项目", "填写金额与审批"],
            "register_hint": "注册后可提交报销",
            "notice_title": "报销单须知",
            "notice_body": "请如实填写报销金额与费用说明；审批通过后线下报销。本期无银行打款对接。",
            "notice_page_title": "办理公告",
            "notice_page_lead": "报销须知与临时通知，点击条目阅读全文。",
            "my_tickets_label": "我的申请",
            "pending_label": "待审申请",
            "records_label": "申请记录",
            "remark_label": "费用说明",
            "fine_label": "报销金额",
            "fine_paid_label": "已线下报销",
            "auto_approve": False,
            "approve_ends_flow": True,
            "contact_channel_label": "票据情况",
            "contact_channel_options": ["票据齐全", "部分票据", "后补票据", "其他"],
            "contact_channel_placeholder": "票据齐全/后补等",
            "next_follow_label": "期望报销日",
            "banners": [
                {"title": "经费项目说明", "lead": "查阅可报销项目与预算说明。"},
                {"title": "提交报销", "lead": "填写金额与费用说明，等待审批。"},
                {"title": "办理公告", "lead": "须知与节点见公告栏。"},
                {"title": "我的申请", "lead": "跟踪审批进度。"},
                {"title": "分类检索", "lead": "按费用类别筛选。"},
            ],
        },
    }
    from app.bake.schema.form_first_entry import apply_form_first_entry

    for preset in out.values():
        apply_form_first_entry(preset)
    return out
