"""OA 申请域 FOLLOWUP_PRESETS（P-01～P-08）。由 tools/gen_oa_apply_domains.py 生成。"""

from __future__ import annotations

from typing import Any, Callable


def build_oa_followup_presets(
    _std_archive_fields: Callable[..., list[dict[str, Any]]],
) -> dict[str, dict[str, Any]]:
    return {
    "DOM-SEAL": {
        "doc": "用章申请：印章事项 + 用章申请。",
        "user_label": "申请人",
        "admin_label": "行政主管（总管）",
        "subadmin_label": "用章管理员",
        "archive_key": "seal_item",
        "archive_label": "印章事项",
        "archive_plural": "印章事项",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "seal_apply",
        "ticket_label": "用章申请",
        "ticket_plural": "用章申请",
        "verbs": {
            "apply": "提交用章",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "印章事项",
        "archive_menu_user": "印章事项目录",
        "auth_eyebrow": "用章申请",
        "auth_lead": "验证码登录；选择印章事项并提交用章，管理员审批后完结。",
        "auth_points": ["验证码登录", "印章事项", "提交用章与审批"],
        "register_hint": "注册后可提交用章",
        "notice_title": "用章申请须知",
        "notice_body": "请如实填写事由；本期无银行/硬件对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请事由",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "印章事项目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交用章", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-FLEET": {
        "doc": "用车申请：车辆 + 用车申请。",
        "user_label": "用车人",
        "admin_label": "车队主管（总管）",
        "subadmin_label": "调度员",
        "archive_key": "fleet_vehicle",
        "archive_label": "车辆",
        "archive_plural": "车辆",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "fleet_apply",
        "ticket_label": "用车申请",
        "ticket_plural": "用车申请",
        "verbs": {
            "apply": "提交用车",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "车辆",
        "archive_menu_user": "车辆目录",
        "auth_eyebrow": "用车申请",
        "auth_lead": "验证码登录；选择车辆并提交用车，管理员审批后完结。",
        "auth_points": ["验证码登录", "车辆", "提交用车与审批"],
        "register_hint": "注册后可提交用车",
        "notice_title": "用车申请须知",
        "notice_body": "请如实填写事由；本期无银行/硬件对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请事由",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "车辆目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交用车", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-CERT": {
        "doc": "开具证明：证明类型 + 开具申请。",
        "user_label": "申请人",
        "admin_label": "综合主管（总管）",
        "subadmin_label": "证明专员",
        "archive_key": "cert_type",
        "archive_label": "证明类型",
        "archive_plural": "证明类型",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "cert_apply",
        "ticket_label": "开具申请",
        "ticket_plural": "开具申请",
        "verbs": {
            "apply": "申请开具",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "证明类型",
        "archive_menu_user": "证明类型目录",
        "auth_eyebrow": "开具证明",
        "auth_lead": "验证码登录；选择证明类型并申请开具，管理员审批后完结。",
        "auth_points": ["验证码登录", "证明类型", "申请开具与审批"],
        "register_hint": "注册后可申请开具",
        "notice_title": "开具申请须知",
        "notice_body": "请如实填写事由；本期无银行/硬件对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请事由",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "证明类型目录", "lead": "浏览可申请事项与说明。"},
            {"title": "申请开具", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-PROMO": {
        "doc": "宣传审批：宣传事项 + 宣传审批。",
        "user_label": "申报人",
        "admin_label": "宣传主管（总管）",
        "subadmin_label": "宣传员",
        "archive_key": "promo_matter",
        "archive_label": "宣传事项",
        "archive_plural": "宣传事项",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "promo_apply",
        "ticket_label": "宣传审批",
        "ticket_plural": "宣传审批",
        "verbs": {
            "apply": "提交方案",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "宣传事项",
        "archive_menu_user": "宣传事项目录",
        "auth_eyebrow": "宣传审批",
        "auth_lead": "验证码登录；选择宣传事项并提交方案，管理员审批后完结。",
        "auth_points": ["验证码登录", "宣传事项", "提交方案与审批"],
        "register_hint": "注册后可提交方案",
        "notice_title": "宣传审批须知",
        "notice_body": "请如实填写事由；本期无银行/硬件对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请事由",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "宣传事项目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交方案", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-FITOUT": {
        "doc": "装修备案：施工区域 + 装修备案。",
        "user_label": "申报人",
        "admin_label": "工程主管（总管）",
        "subadmin_label": "备案员",
        "archive_key": "fitout_site",
        "archive_label": "施工区域",
        "archive_plural": "施工区域",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "fitout_apply",
        "ticket_label": "装修备案",
        "ticket_plural": "装修备案",
        "verbs": {
            "apply": "提交备案",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "施工区域",
        "archive_menu_user": "施工区域目录",
        "auth_eyebrow": "装修备案",
        "auth_lead": "验证码登录；选择施工区域并提交备案，管理员审批后完结。",
        "auth_points": ["验证码登录", "施工区域", "提交备案与审批"],
        "register_hint": "注册后可提交备案",
        "notice_title": "装修备案须知",
        "notice_body": "请如实填写事由；本期无银行/硬件对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请事由",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "施工区域目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交备案", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-ACAD": {
        "doc": "学籍异动：异动事项 + 异动申请。",
        "user_label": "学生",
        "admin_label": "教务主管（总管）",
        "subadmin_label": "教务员",
        "archive_key": "acad_matter",
        "archive_label": "异动事项",
        "archive_plural": "异动事项",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "acad_apply",
        "ticket_label": "异动申请",
        "ticket_plural": "异动申请",
        "verbs": {
            "apply": "提交申请",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "异动事项",
        "archive_menu_user": "异动事项目录",
        "auth_eyebrow": "学籍异动",
        "auth_lead": "验证码登录；选择异动事项并提交申请，管理员审批后完结。",
        "auth_points": ["验证码登录", "异动事项", "提交申请与审批"],
        "register_hint": "注册后可提交申请",
        "notice_title": "异动申请须知",
        "notice_body": "请如实填写事由；本期无银行/硬件对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请事由",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "异动事项目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交申请", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-TRIP": {
        "doc": "出差加班：事项类型 + 出差加班单。",
        "user_label": "员工",
        "admin_label": "人事主管（总管）",
        "subadmin_label": "考勤员",
        "archive_key": "trip_matter",
        "archive_label": "事项类型",
        "archive_plural": "事项类型",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "trip_apply",
        "ticket_label": "出差加班单",
        "ticket_plural": "出差加班单",
        "verbs": {
            "apply": "提交申请",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "事项类型",
        "archive_menu_user": "事项类型目录",
        "auth_eyebrow": "出差加班",
        "auth_lead": "验证码登录；选择事项类型并提交申请，管理员审批后完结。",
        "auth_points": ["验证码登录", "事项类型", "提交申请与审批"],
        "register_hint": "注册后可提交申请",
        "notice_title": "出差加班单须知",
        "notice_body": "请如实填写事由；本期无银行/硬件对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请事由",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "事项类型目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交申请", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-EXPENSE": {
        "doc": "经费报销：经费项目 + 报销单。",
        "user_label": "报销人",
        "admin_label": "财务主管（总管）",
        "subadmin_label": "报销审核员",
        "archive_key": "expense_project",
        "archive_label": "经费项目",
        "archive_plural": "经费项目",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "expense_apply",
        "ticket_label": "报销单",
        "ticket_plural": "报销单",
        "verbs": {
            "apply": "提交报销",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "经费项目",
        "archive_menu_user": "经费项目目录",
        "auth_eyebrow": "经费报销",
        "auth_lead": "验证码登录；选择经费项目并提交报销，管理员审批后完结。",
        "auth_points": ["验证码登录", "经费项目", "提交报销与审批"],
        "register_hint": "注册后可提交报销",
        "notice_title": "报销单须知",
        "notice_body": "请如实填写事由；本期无银行/硬件对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请事由",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "经费项目目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交报销", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    }
