"""学工预设 FOLLOWUP_PRESETS（P-12～P-16）。"""

from __future__ import annotations

from typing import Any, Callable


def build_stuwork_followup_presets(
    _std_archive_fields: Callable[..., list[dict[str, Any]]],
) -> dict[str, dict[str, Any]]:
    return {
    "DOM-CREDIT": {
        "doc": "第二课堂认定：认定项目 + 学分认定。",
        "user_label": "学生",
        "admin_label": "学工主管（总管）",
        "subadmin_label": "认定专员",
        "archive_key": "credit_item",
        "archive_label": "认定项目",
        "archive_plural": "认定项目",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "credit_apply",
        "ticket_label": "学分认定",
        "ticket_plural": "学分认定",
        "verbs": {
            "apply": "提交认定",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "认定项目",
        "archive_menu_user": "认定项目目录",
        "auth_eyebrow": "第二课堂认定",
        "auth_lead": "验证码登录；选择认定项目并提交认定，管理员审批后完结。",
        "auth_points": ["验证码登录", "认定项目", "提交认定与审批"],
        "register_hint": "注册后可提交认定",
        "notice_title": "学分认定须知",
        "notice_body": "请如实填写说明与佐证；本期无学信网/银行对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请说明",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "认定项目目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交认定", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-LABOR": {
        "doc": "劳动时长认定：劳动项目 + 时长认定。",
        "user_label": "学生",
        "admin_label": "学工主管（总管）",
        "subadmin_label": "劳动专员",
        "archive_key": "labor_item",
        "archive_label": "劳动项目",
        "archive_plural": "劳动项目",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "labor_apply",
        "ticket_label": "时长认定",
        "ticket_plural": "时长认定",
        "verbs": {
            "apply": "提交时长",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "劳动项目",
        "archive_menu_user": "劳动项目目录",
        "auth_eyebrow": "劳动时长认定",
        "auth_lead": "验证码登录；选择劳动项目并提交时长，管理员审批后完结。",
        "auth_points": ["验证码登录", "劳动项目", "提交时长与审批"],
        "register_hint": "注册后可提交时长",
        "notice_title": "时长认定须知",
        "notice_body": "请如实填写说明与佐证；本期无学信网/银行对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请说明",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "劳动项目目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交时长", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-EVAL": {
        "doc": "网上评教：评教课程 + 评教卷（提交即多维打分完结）。",
        "user_label": "学生",
        "admin_label": "教务主管（总管）",
        "subadmin_label": "评教员",
        "archive_key": "eval_course",
        "archive_label": "评教课程",
        "archive_plural": "评教课程",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "eval_sheet",
        "ticket_label": "评教卷",
        "ticket_plural": "评教卷",
        "verbs": {
            "apply": "提交评教",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待提交",
            "approved": "已评教",
            "rejected": "已作废",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "评教课程",
        "archive_menu_user": "评教课程目录",
        "auth_eyebrow": "网上评教",
        "auth_lead": "验证码登录；选择评教课程，当场按维度打分并填写评语，提交即完结。",
        "auth_points": ["验证码登录", "评教课程", "多维评分与评语"],
        "register_hint": "注册后可提交评教",
        "notice_title": "评教须知",
        "notice_body": "请如实按维度评分并填写评语；提交后即时入档。本期无学信网对接。",
        "notice_page_title": "评教公告",
        "notice_page_lead": "评教节点与须知，点击条目阅读全文。",
        "my_tickets_label": "我的评教",
        "pending_label": "评教调剂",
        "records_label": "评教记录",
        "remark_label": "评教评语",
        "auto_approve": True,
        "allow_rating": True,
        "approve_ends_flow": True,
        "allow_anonymous_rating": True,
        "rating_dims": [
            {"key": "content", "label": "教学内容"},
            {"key": "attitude", "label": "教学态度"},
            {"key": "outcome", "label": "课程收获"},
        ],
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上评教", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "评教课程目录", "lead": "浏览本学期可评课程。"},
            {"title": "提交评教", "lead": "选课当场按维度打分并填写评语，提交即完结。"},
            {"title": "评教公告", "lead": "评教须知与节点见公告栏。"},
            {"title": "我的评教", "lead": "查看已提交的评教记录。"},
            {"title": "分类检索", "lead": "按课程类型筛选。"},
        ],
    },
    "DOM-MORAL": {
        "doc": "综测申报：测评指标 + 加减分申请。",
        "user_label": "学生",
        "admin_label": "学工主管（总管）",
        "subadmin_label": "综测专员",
        "archive_key": "moral_item",
        "archive_label": "测评指标",
        "archive_plural": "测评指标",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "moral_apply",
        "ticket_label": "加减分申请",
        "ticket_plural": "加减分申请",
        "verbs": {
            "apply": "提交申报",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "测评指标",
        "archive_menu_user": "测评指标目录",
        "auth_eyebrow": "综测申报",
        "auth_lead": "验证码登录；选择测评指标并提交申报，管理员审批后完结。",
        "auth_points": ["验证码登录", "测评指标", "提交申报与审批"],
        "register_hint": "注册后可提交申报",
        "notice_title": "加减分申请须知",
        "notice_body": "请如实填写说明与佐证；本期无学信网/银行对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请说明",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "测评指标目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交申报", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    "DOM-AWARD": {
        "doc": "成果登记：成果类型 + 成果登记。",
        "user_label": "学生",
        "admin_label": "教务主管（总管）",
        "subadmin_label": "成果专员",
        "archive_key": "award_item",
        "archive_label": "成果类型",
        "archive_plural": "成果类型",
        "archive_fields": _std_archive_fields(
            "名称",
            "责任部门",
            "说明",
            "状态",
            ["开放", "暂停", "关闭"],
            "分类",
            "可申请",
        ),
        "ticket_key": "award_apply",
        "ticket_label": "成果登记",
        "ticket_plural": "成果登记",
        "verbs": {
            "apply": "提交登记",
            "approve": "通过",
            "reject": "驳回",
            "return": "完结",
            "remind": "催办",
        },
        "states": {
            "pending": "待审",
            "approved": "已通过",
            "rejected": "已驳回",
            "returned": "已完结",
            "overdue": "已逾期",
        },
        "archive_menu_admin": "成果类型",
        "archive_menu_user": "成果类型目录",
        "auth_eyebrow": "成果登记",
        "auth_lead": "验证码登录；选择成果类型并提交登记，管理员审批后完结。",
        "auth_points": ["验证码登录", "成果类型", "提交登记与审批"],
        "register_hint": "注册后可提交登记",
        "notice_title": "成果登记须知",
        "notice_body": "请如实填写说明与佐证；本期无学信网/银行对接。",
        "notice_page_title": "办理公告",
        "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
        "my_tickets_label": "我的申请",
        "pending_label": "待审申请",
        "records_label": "申请记录",
        "remark_label": "申请说明",
        "auto_approve": False,
        "contact_channel_label": "办理方式",
        "contact_channel_options": ["线上申请", "窗口补录", "其他"],
        "contact_channel_placeholder": "线上/窗口等",
        "next_follow_label": "期望办结日",
        "banners": [
            {"title": "成果类型目录", "lead": "浏览可申请事项与说明。"},
            {"title": "提交登记", "lead": "选择事项提交申请，等待审批。"},
            {"title": "办理公告", "lead": "须知与节点见公告栏。"},
            {"title": "我的申请", "lead": "跟踪审批进度。"},
            {"title": "分类检索", "lead": "按类型筛选事项。"},
        ],
    },
    }
