"""长尾预设 FOLLOWUP_PRESETS（P-18、P-23～P-29）。"""

from __future__ import annotations

from typing import Any, Callable


def build_tail_followup_presets(
    _std_archive_fields: Callable[..., list[dict[str, Any]]],
) -> dict[str, dict[str, Any]]:
    return {
"DOM-CARPASS": {
    "doc": "车辆通行证：通行区域 + 通行证申请。",
    "user_label": "申请人",
    "admin_label": "业务主管（总管）",
    "subadmin_label": "车证管理员",
    "archive_key": "pass_zone",
    "archive_label": "通行区域",
    "archive_plural": "通行区域",
    "archive_fields": _std_archive_fields(
        "名称",
        "责任部门",
        "说明",
        "状态",
        ["开放", "暂停", "关闭"],
        "分类",
        "可申请",
    ),
    "stock_display": "toggle",
    "ticket_key": "carpass_apply",
    "ticket_label": "通行证申请",
    "ticket_plural": "通行证申请",
    "verbs": {
        "apply": "提交备案",
        "approve": "通过",
        "reject": "驳回",
        "return": "完结",
        "remind": "催办",
    },
    "states": {
        "pending": "待审",
        "approved": "已通过",
        "rejected": "已驳回",
        "returned": "已完结",
        "overdue": "已逾期",
    },
    "archive_menu_admin": "通行区域",
    "archive_menu_user": "通行区域目录",
    "auth_eyebrow": "车辆通行证",
    "auth_lead": "验证码登录；选择通行区域并提交备案，管理员审批后完结。",
    "auth_points": ["验证码登录", "通行区域", "提交备案与审批"],
    "register_hint": "注册后可办理",
    "notice_title": "车辆通行证须知",
    "notice_body": "请如实填写说明与附件；本期无外部系统对接。",
    "notice_page_title": "办理公告",
    "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
    "my_tickets_label": "我的申请",
    "pending_label": "待审申请",
    "records_label": "申请记录",
    "remark_label": "申请说明",
    "auto_approve": False,
    "approve_ends_flow": True,
    "issue_pass_code": True,
    "pass_code_label": "通行码",
    "contact_channel_label": "办理类型",
    "contact_channel_options": ["临时车牌", "长期备案", "施工车辆", "其他"],
    "contact_channel_placeholder": "选择类型",
    "next_follow_label": "期望办结日",
    "banners": [
        {"title": "通行区域目录", "lead": "浏览可办理事项。"},
        {"title": "提交备案", "lead": "填写说明提交申请。"},
        {"title": "办理公告", "lead": "须知见公告栏。"},
        {"title": "我的申请", "lead": "跟踪审批进度。"},
        {"title": "分类检索", "lead": "按类型筛选。"},
    ],
},

"DOM-LISTING": {
    "doc": "房源带看：房源 + 带看跟进。",
    "user_label": "申请人",
    "admin_label": "业务主管（总管）",
    "subadmin_label": "置业顾问",
    "archive_key": "listing",
    "archive_label": "房源",
    "archive_plural": "房源",
    "archive_fields": _std_archive_fields(
        "名称",
        "责任部门",
        "说明",
        "状态",
        ["开放", "暂停", "关闭"],
        "分类",
        "可申请",
    ),
    "stock_display": "toggle",
    "ticket_key": "listing_follow",
    "ticket_label": "带看跟进",
    "ticket_plural": "带看跟进",
    "verbs": {
        "apply": "登记意向",
        "approve": "通过",
        "reject": "驳回",
        "return": "完结",
        "remind": "催办",
    },
    "states": {
        "pending": "待审",
        "approved": "已通过",
        "rejected": "已驳回",
        "returned": "已完结",
        "overdue": "已逾期",
    },
    "archive_menu_admin": "房源",
    "archive_menu_user": "房源目录",
    "auth_eyebrow": "房源带看",
    "auth_lead": "验证码登录；选择房源并登记意向，管理员审批后完结。",
    "auth_points": ["验证码登录", "房源", "登记意向与审批"],
    "register_hint": "注册后可办理",
    "notice_title": "房源带看须知",
    "notice_body": "请如实填写说明与附件；本期无外部系统对接。",
    "notice_page_title": "办理公告",
    "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
    "my_tickets_label": "我的申请",
    "pending_label": "待审申请",
    "records_label": "申请记录",
    "remark_label": "申请说明",
    "auto_approve": False,
    "approve_ends_flow": True,
    "contact_channel_label": "办理类型",
    "contact_channel_options": ["电话约看", "到店带看", "线上沟通", "其他"],
    "contact_channel_placeholder": "选择类型",
    "next_follow_label": "期望办结日",
    "banners": [
        {"title": "房源目录", "lead": "浏览可办理事项。"},
        {"title": "登记意向", "lead": "填写说明提交申请。"},
        {"title": "办理公告", "lead": "须知见公告栏。"},
        {"title": "我的申请", "lead": "跟踪审批进度。"},
        {"title": "分类检索", "lead": "按类型筛选。"},
    ],
},

"DOM-PROCURE": {
    "doc": "采购申购：采购品目 + 申购单。",
    "user_label": "申请人",
    "admin_label": "业务主管（总管）",
    "subadmin_label": "采购专员",
    "archive_key": "procure_item",
    "archive_label": "采购品目",
    "archive_plural": "采购品目",
    "archive_fields": _std_archive_fields(
        "名称",
        "责任部门",
        "说明",
        "状态",
        ["开放", "暂停", "关闭"],
        "分类",
        "可申请",
    ),
    "stock_display": "toggle",
    "ticket_key": "procure_apply",
    "ticket_label": "申购单",
    "ticket_plural": "申购单",
    "verbs": {
        "apply": "提交申购",
        "approve": "通过",
        "reject": "驳回",
        "return": "完结",
        "remind": "催办",
    },
    "states": {
        "pending": "待审",
        "approved": "已通过",
        "rejected": "已驳回",
        "returned": "已完结",
        "overdue": "已逾期",
    },
    "archive_menu_admin": "采购品目",
    "archive_menu_user": "采购品目目录",
    "auth_eyebrow": "采购申购",
    "auth_lead": "验证码登录；选择采购品目并提交申购，管理员审批后完结。",
    "auth_points": ["验证码登录", "采购品目", "提交申购与审批"],
    "register_hint": "注册后可办理",
    "notice_title": "采购申购须知",
    "notice_body": "请如实填写说明与附件；本期无外部系统对接。",
    "notice_page_title": "办理公告",
    "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
    "my_tickets_label": "我的申请",
    "pending_label": "待审申请",
    "records_label": "申请记录",
    "remark_label": "申请说明",
    "auto_approve": False,
    "approve_ends_flow": True,
    "contact_channel_label": "办理类型",
    "contact_channel_options": ["常规采购", "紧急采购", "集中采购", "其他"],
    "contact_channel_placeholder": "选择类型",
    "next_follow_label": "期望办结日",
    "banners": [
        {"title": "采购品目目录", "lead": "浏览可办理事项。"},
        {"title": "提交申购", "lead": "填写说明提交申请。"},
        {"title": "办理公告", "lead": "须知见公告栏。"},
        {"title": "我的申请", "lead": "跟踪审批进度。"},
        {"title": "分类检索", "lead": "按类型筛选。"},
    ],
},

"DOM-CLUB": {
    "doc": "社团年审：社团事项 + 注册年审。",
    "user_label": "申请人",
    "admin_label": "业务主管（总管）",
    "subadmin_label": "社团专员",
    "archive_key": "club_item",
    "archive_label": "社团事项",
    "archive_plural": "社团事项",
    "archive_fields": _std_archive_fields(
        "名称",
        "责任部门",
        "说明",
        "状态",
        ["开放", "暂停", "关闭"],
        "分类",
        "可申请",
    ),
    "stock_display": "toggle",
    "ticket_key": "club_apply",
    "ticket_label": "注册年审",
    "ticket_plural": "注册年审",
    "verbs": {
        "apply": "提交材料",
        "approve": "通过",
        "reject": "驳回",
        "return": "完结",
        "remind": "催办",
    },
    "states": {
        "pending": "待审",
        "approved": "已通过",
        "rejected": "已驳回",
        "returned": "已完结",
        "overdue": "已逾期",
    },
    "archive_menu_admin": "社团事项",
    "archive_menu_user": "社团事项目录",
    "auth_eyebrow": "社团年审",
    "auth_lead": "验证码登录；选择社团事项并提交材料，管理员审批后完结。",
    "auth_points": ["验证码登录", "社团事项", "提交材料与审批"],
    "register_hint": "注册后可办理",
    "notice_title": "社团年审须知",
    "notice_body": "请如实填写说明与附件；本期无外部系统对接。",
    "notice_page_title": "办理公告",
    "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
    "my_tickets_label": "我的申请",
    "pending_label": "待审申请",
    "records_label": "申请记录",
    "remark_label": "申请说明",
    "auto_approve": False,
    "approve_ends_flow": True,
    "contact_channel_label": "办理类型",
    "contact_channel_options": ["成立注册", "年审", "变更", "其他"],
    "contact_channel_placeholder": "选择类型",
    "next_follow_label": "期望办结日",
    "banners": [
        {"title": "社团事项目录", "lead": "浏览可办理事项。"},
        {"title": "提交材料", "lead": "填写说明提交申请。"},
        {"title": "办理公告", "lead": "须知见公告栏。"},
        {"title": "我的申请", "lead": "跟踪审批进度。"},
        {"title": "分类检索", "lead": "按类型筛选。"},
    ],
},

"DOM-PROJ": {
    "doc": "项目申报：申报项目 + 申报/检查。",
    "user_label": "申请人",
    "admin_label": "业务主管（总管）",
    "subadmin_label": "项目专员",
    "archive_key": "proj_item",
    "archive_label": "申报项目",
    "archive_plural": "申报项目",
    "archive_fields": _std_archive_fields(
        "名称",
        "责任部门",
        "说明",
        "状态",
        ["开放", "暂停", "关闭"],
        "分类",
        "可申请",
    ),
    "stock_display": "toggle",
    "ticket_key": "proj_apply",
    "ticket_label": "申报/检查",
    "ticket_plural": "申报/检查",
    "verbs": {
        "apply": "提交申报",
        "approve": "通过",
        "reject": "驳回",
        "return": "完结",
        "remind": "催办",
    },
    "states": {
        "pending": "待审",
        "approved": "已通过",
        "rejected": "已驳回",
        "returned": "已完结",
        "overdue": "已逾期",
    },
    "archive_menu_admin": "申报项目",
    "archive_menu_user": "申报项目目录",
    "auth_eyebrow": "项目申报",
    "auth_lead": "验证码登录；选择申报项目并提交申报，管理员审批后完结。",
    "auth_points": ["验证码登录", "申报项目", "提交申报与审批"],
    "register_hint": "注册后可办理",
    "notice_title": "项目申报须知",
    "notice_body": "请如实填写说明与附件；本期无外部系统对接。",
    "notice_page_title": "办理公告",
    "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
    "my_tickets_label": "我的申请",
    "pending_label": "待审申请",
    "records_label": "申请记录",
    "remark_label": "申请说明",
    "auto_approve": False,
    "approve_ends_flow": True,
    "contact_channel_label": "办理类型",
    "contact_channel_options": ["立项", "中期", "结题", "其他"],
    "contact_channel_placeholder": "选择类型",
    "next_follow_label": "期望办结日",
    "banners": [
        {"title": "申报项目目录", "lead": "浏览可办理事项。"},
        {"title": "提交申报", "lead": "填写说明提交申请。"},
        {"title": "办理公告", "lead": "须知见公告栏。"},
        {"title": "我的申请", "lead": "跟踪审批进度。"},
        {"title": "分类检索", "lead": "按类型筛选。"},
    ],
},

"DOM-ETHIC": {
    "doc": "材料审核：审核事项 + 材料审核。",
    "user_label": "申请人",
    "admin_label": "业务主管（总管）",
    "subadmin_label": "审核秘书",
    "archive_key": "ethic_item",
    "archive_label": "审核事项",
    "archive_plural": "审核事项",
    "archive_fields": _std_archive_fields(
        "名称",
        "责任部门",
        "说明",
        "状态",
        ["开放", "暂停", "关闭"],
        "分类",
        "可申请",
    ),
    "stock_display": "toggle",
    "ticket_key": "ethic_apply",
    "ticket_label": "材料审核",
    "ticket_plural": "材料审核",
    "verbs": {
        "apply": "提交材料",
        "approve": "通过",
        "reject": "驳回",
        "return": "完结",
        "remind": "催办",
    },
    "states": {
        "pending": "待审",
        "approved": "已通过",
        "rejected": "已驳回",
        "returned": "已完结",
        "overdue": "已逾期",
    },
    "archive_menu_admin": "审核事项",
    "archive_menu_user": "审核事项目录",
    "auth_eyebrow": "材料审核",
    "auth_lead": "验证码登录；选择审核事项并提交材料，管理员审批后完结。",
    "auth_points": ["验证码登录", "审核事项", "提交材料与审批"],
    "register_hint": "注册后可办理",
    "notice_title": "材料审核须知",
    "notice_body": "请如实填写说明与附件；本期无外部系统对接。",
    "notice_page_title": "办理公告",
    "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
    "my_tickets_label": "我的申请",
    "pending_label": "待审申请",
    "records_label": "申请记录",
    "remark_label": "申请说明",
    "auto_approve": False,
    "approve_ends_flow": True,
    "contact_channel_label": "办理类型",
    "contact_channel_options": ["伦理", "开题", "答辩", "其他"],
    "contact_channel_placeholder": "选择类型",
    "next_follow_label": "期望办结日",
    "banners": [
        {"title": "审核事项目录", "lead": "浏览可办理事项。"},
        {"title": "提交材料", "lead": "填写说明提交申请。"},
        {"title": "办理公告", "lead": "须知见公告栏。"},
        {"title": "我的申请", "lead": "跟踪审批进度。"},
        {"title": "分类检索", "lead": "按类型筛选。"},
    ],
},

"DOM-PARTY": {
    "doc": "党员发展：发展阶段 + 阶段材料。",
    "user_label": "申请人",
    "admin_label": "业务主管（总管）",
    "subadmin_label": "组织员",
    "archive_key": "party_stage",
    "archive_label": "发展阶段",
    "archive_plural": "发展阶段",
    "archive_fields": _std_archive_fields(
        "名称",
        "责任部门",
        "说明",
        "状态",
        ["开放", "暂停", "关闭"],
        "分类",
        "可申请",
    ),
    "stock_display": "toggle",
    "ticket_key": "party_apply",
    "ticket_label": "阶段材料",
    "ticket_plural": "阶段材料",
    "verbs": {
        "apply": "提交材料",
        "approve": "通过",
        "reject": "驳回",
        "return": "完结",
        "remind": "催办",
    },
    "states": {
        "pending": "待审",
        "approved": "已通过",
        "rejected": "已驳回",
        "returned": "已完结",
        "overdue": "已逾期",
    },
    "archive_menu_admin": "发展阶段",
    "archive_menu_user": "发展阶段目录",
    "auth_eyebrow": "党员发展",
    "auth_lead": "验证码登录；选择发展阶段并提交材料，管理员审批后完结。",
    "auth_points": ["验证码登录", "发展阶段", "提交材料与审批"],
    "register_hint": "注册后可办理",
    "notice_title": "党员发展须知",
    "notice_body": "请如实填写说明与附件；本期无外部系统对接。",
    "notice_page_title": "办理公告",
    "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
    "my_tickets_label": "我的申请",
    "pending_label": "待审申请",
    "records_label": "申请记录",
    "remark_label": "申请说明",
    "auto_approve": False,
    "approve_ends_flow": True,
    "contact_channel_label": "办理类型",
    "contact_channel_options": ["申请", "积极分子", "发展对象", "其他"],
    "contact_channel_placeholder": "选择类型",
    "next_follow_label": "期望办结日",
    "banners": [
        {"title": "发展阶段目录", "lead": "浏览可办理事项。"},
        {"title": "提交材料", "lead": "填写说明提交申请。"},
        {"title": "办理公告", "lead": "须知见公告栏。"},
        {"title": "我的申请", "lead": "跟踪审批进度。"},
        {"title": "分类检索", "lead": "按类型筛选。"},
    ],
},

"DOM-CONTRACT": {
    "doc": "合同审批：合同类型 + 合同审批。",
    "user_label": "申请人",
    "admin_label": "业务主管（总管）",
    "subadmin_label": "合同专员",
    "archive_key": "contract_type",
    "archive_label": "合同类型",
    "archive_plural": "合同类型",
    "archive_fields": _std_archive_fields(
        "名称",
        "责任部门",
        "说明",
        "状态",
        ["开放", "暂停", "关闭"],
        "分类",
        "可申请",
    ),
    "stock_display": "toggle",
    "ticket_key": "contract_apply",
    "ticket_label": "合同审批",
    "ticket_plural": "合同审批",
    "verbs": {
        "apply": "提交合同",
        "approve": "通过",
        "reject": "驳回",
        "return": "完结",
        "remind": "催办",
    },
    "states": {
        "pending": "待审",
        "approved": "已通过",
        "rejected": "已驳回",
        "returned": "已完结",
        "overdue": "已逾期",
    },
    "archive_menu_admin": "合同类型",
    "archive_menu_user": "合同类型目录",
    "auth_eyebrow": "合同审批",
    "auth_lead": "验证码登录；选择合同类型并提交合同，管理员审批后完结。",
    "auth_points": ["验证码登录", "合同类型", "提交合同与审批"],
    "register_hint": "注册后可办理",
    "notice_title": "合同审批须知",
    "notice_body": "请如实填写说明与附件；本期无外部系统对接。",
    "notice_page_title": "办理公告",
    "notice_page_lead": "办理须知与临时通知，点击条目阅读全文。",
    "my_tickets_label": "我的申请",
    "pending_label": "待审申请",
    "records_label": "申请记录",
    "remark_label": "申请说明",
    "auto_approve": False,
    "approve_ends_flow": True,
    "contact_channel_label": "办理类型",
    "contact_channel_options": ["新签", "续签", "变更", "其他"],
    "contact_channel_placeholder": "选择类型",
    "next_follow_label": "期望办结日",
    "banners": [
        {"title": "合同类型目录", "lead": "浏览可办理事项。"},
        {"title": "提交合同", "lead": "填写说明提交申请。"},
        {"title": "办理公告", "lead": "须知见公告栏。"},
        {"title": "我的申请", "lead": "跟踪审批进度。"},
        {"title": "分类检索", "lead": "按类型筛选。"},
    ],
},
    }
