"""领域目录 — MEDIA/MUSIC/FORUM/BLOG。"""

from __future__ import annotations

from app.bake.gate_contracts import (
    gate_archive_favorites,
    gate_archive_ticket,
)

DOMAINS: dict = {
    "DOM-MEDIA": {
        "label": "影视综",
        "keywords": ["影视", "电影", "电视剧", "综艺", "视频点播", "在线视频", "片库"],
        "match_hint": "适用：影视综点播、片单收藏。勿与音乐（歌曲曲库）或博客（文章 CMS）混淆。",
        "entities": ["Media", "Category", "Favorite", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["浏览片单 → 播放 → 收藏"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "片单检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "收藏 / 想看", "status": "flow"},
            {"name": "我的收藏", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "协同过滤推荐", "status": "out_of_mvp"},
            {"name": "直播与弹幕", "status": "out_of_mvp"},
            {"name": "转码 CDN", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["协同过滤推荐", "直播与弹幕", "转码 CDN"],
        "themes": [
            {"id": "media-cinema", "label": "影院午夜"},
            {"id": "media-amber", "label": "暖幕琥珀"},
            {"id": "media-teal", "label": "荧幕青绿"},
            {"id": "media-night", "label": "观影深色"},
        ],
        "gate": gate_archive_favorites(
            archive_feature="片单检索",
            favorites_feature="收藏 / 想看",
            users_feature="用户管理",
            category_feature="分类管理",
        ),
        "portal_banners": True,
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "media",
        },
    },
    "DOM-MUSIC": {
        "label": "音乐",
        "keywords": ["音乐", "歌曲", "歌单", "在线音乐", "音乐播放器", "听歌", "曲库"],
        "match_hint": "适用：在线音乐曲库、歌单收藏。勿与影视综或博客混淆。",
        "entities": ["Track", "Category", "Favorite", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["浏览曲库 → 播放 → 收藏"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "曲库检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "收藏 / 喜欢", "status": "flow"},
            {"name": "我的收藏", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "协同过滤推荐", "status": "out_of_mvp"},
            {"name": "歌词同步", "status": "out_of_mvp"},
            {"name": "真转码 CDN", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["协同过滤推荐", "歌词同步", "真转码 CDN"],
        "themes": [
            {"id": "music-vinyl", "label": "黑胶午夜"},
            {"id": "music-amber", "label": "暖光耳机"},
            {"id": "music-teal", "label": "波形青绿"},
            {"id": "music-night", "label": "夜听深色"},
        ],
        "gate": gate_archive_favorites(
            archive_feature="曲库检索",
            favorites_feature="收藏 / 喜欢",
            users_feature="用户管理",
            category_feature="分类管理",
        ),
        "portal_banners": True,
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "track",
        },
    },
    "DOM-FORUM": {
        "label": "论坛",
        "keywords": ["论坛", "BBS", "贴吧", "社区帖子", "板块", "发帖", "回帖", "楼中楼"],
        "match_hint": "适用：BBS 论坛发帖回帖审核。勿与博客（单向文章收藏）混淆。",
        "entities": ["Post", "Category", "Reply", "Tag", "Attach", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["发帖 / 浏览 → 回复 → 版主审核展示"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "帖子检索", "status": "domain"},
            {"name": "用户发帖", "status": "flow"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "回复 / 楼中楼", "status": "flow"},
            {"name": "回复记录", "status": "module"},
            {"name": "富文本编辑", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "标签与附件（库表/ER）", "status": "module"},
            {"name": "实时私信", "status": "out_of_mvp"},
            {"name": "无限深度树形嵌套引擎", "status": "out_of_mvp"},
            {"name": "富文本协同编辑", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["实时私信", "无限深度树形嵌套引擎", "富文本协同编辑"],
        "themes": [
            {"id": "forum-ink", "label": "论坛墨蓝"},
            {"id": "forum-amber", "label": "暖帖琥珀"},
            {"id": "forum-teal", "label": "版块青绿"},
            {"id": "forum-night", "label": "夜读深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="帖子检索",
            flow_feature="回复 / 楼中楼",
            records_feature="回复记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
            user_publish=True,
            publish_feature="用户发帖",
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "reply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "post",
            "allow_multi_ticket": True,
            "archive_tag_table": "tag",
            "archive_item_tag_table": "post_tag",
        },
    },
    "DOM-BLOG": {
        "label": "博客",
        "keywords": ["博客", "个人博客", "文章系统", "资讯发布", "CMS", "博文"],
        "match_hint": "适用：个人博客/资讯文章浏览收藏。勿与论坛（回帖互动）或影视综混淆。",
        "entities": ["Article", "Category", "Favorite", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["浏览文章 → 收藏"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "文章检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "收藏 / 订阅", "status": "flow"},
            {"name": "我的收藏", "status": "module"},
            {"name": "富文本编辑", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "富文本协同编辑", "status": "out_of_mvp"},
            {"name": "多作者工作流引擎", "status": "out_of_mvp"},
            {"name": "SEO / CDN 分发", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["富文本协同编辑", "多作者工作流引擎", "SEO / CDN 分发"],
        "themes": [
            {"id": "blog-ink", "label": "博文墨蓝"},
            {"id": "blog-grove", "label": "随笔青绿"},
            {"id": "blog-clay", "label": "暖陶阅读"},
            {"id": "blog-night", "label": "夜读深色"},
        ],
        "gate": gate_archive_favorites(
            archive_feature="文章检索",
            favorites_feature="收藏 / 订阅",
            users_feature="用户管理",
            category_feature="分类管理",
        ),
        "portal_banners": True,
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "article",
        },
    }
}
