"""领域目录 — OA 申请预设（P-01～P-08）。"""

from __future__ import annotations

from app.bake.gate_contracts import gate_archive_ticket

DOMAINS: dict = {
    "DOM-SEAL": {
        "label": "用章申请",
        # 词表只做硬分流；长尾说法交给 match_recommend（见 match_hint）
        "keywords": [
            "用章", "印章申请", "公章使用", "用印申请", "行政用章", "用章审批",
            "行政印章", "印章使用", "印章审批", "用印审批",
        ],
        "match_hint": (
            "适用：行政印章/合同章用章申请与审批。"
            "勿与资助申请、请假、开具证明或合同正文登记单级审批混淆。"
        ),
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["本人申请填单（选事项） → 提交用章 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "印章事项", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "用章申请审核", "status": "flow"},
            {"name": "用章申请记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "seal-teal", "label": "用章申请青绿"},
            {"id": "seal-sand", "label": "用章申请暖沙"},
            {"id": "seal-slate", "label": "用章申请灰青"},
            {"id": "seal-night", "label": "用章申请深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="印章事项",
            flow_feature="用章申请审核",
            records_feature="用章申请记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "seal_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "seal_item",
        },
    },
    "DOM-FLEET": {
        "label": "用车申请",
        # 词表只做硬分流；长尾说法交给 match_recommend
        "keywords": ["用车申请", "公务用车", "派车申请", "车辆申请", "公车预约", "用车审批"],
        "match_hint": (
            "适用：公务用车选车申请与审批（台账级调度，无时段冲突引擎）。"
            "勿与车位预约、请假出差或四轮商业租车（DOM-CARRENT，按日取还）混淆。"
        ),
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["本人申请填单（选事项） → 提交用车 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "车辆", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "用车申请审核", "status": "flow"},
            {"name": "用车申请记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "fleet-teal", "label": "用车申请青绿"},
            {"id": "fleet-sand", "label": "用车申请暖沙"},
            {"id": "fleet-slate", "label": "用车申请灰青"},
            {"id": "fleet-night", "label": "用车申请深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="车辆",
            flow_feature="用车申请审核",
            records_feature="用车申请记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "fleet_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "fleet_vehicle",
        },
    },
    "DOM-CERT": {
        "label": "开具证明",
        # 词表只做硬分流；长尾说法交给 match_recommend
        "keywords": ["开具证明", "在读证明", "在职证明", "成绩单证明", "证明申请", "开证明"],
        "match_hint": "适用：在读/在职/成绩单等证明开具申请审核。勿与成绩更正、资助申请或用章混淆。",
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["本人申请填单（选事项） → 申请开具 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "证明类型", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "开具申请审核", "status": "flow"},
            {"name": "开具申请记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "cert-teal", "label": "开具证明青绿"},
            {"id": "cert-sand", "label": "开具证明暖沙"},
            {"id": "cert-slate", "label": "开具证明灰青"},
            {"id": "cert-night", "label": "开具证明深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="证明类型",
            flow_feature="开具申请审核",
            records_feature="开具申请记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "cert_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "cert_type",
        },
    },
    "DOM-PROMO": {
        "label": "宣传审批",
        # 词表只做硬分流；长尾说法交给 match_recommend
        "keywords": ["横幅审批", "海报审批", "户外宣传", "宣传审批", "条幅申请", "宣传品审批"],
        "match_hint": "适用：横幅/海报/户外宣传方案审批。勿与活动报名或物业报修混淆。",
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["本人申请填单（选事项） → 提交方案 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "宣传事项", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "宣传审批审核", "status": "flow"},
            {"name": "宣传审批记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "promo-teal", "label": "宣传审批青绿"},
            {"id": "promo-sand", "label": "宣传审批暖沙"},
            {"id": "promo-slate", "label": "宣传审批灰青"},
            {"id": "promo-night", "label": "宣传审批深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="宣传事项",
            flow_feature="宣传审批审核",
            records_feature="宣传审批记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "promo_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "promo_matter",
        },
    },
    "DOM-FITOUT": {
        "label": "装修备案",
        # 词表只做硬分流；长尾说法交给 match_recommend
        "keywords": ["装修备案", "进场施工", "施工备案", "装修申请", "进场申请", "装修审批"],
        "match_hint": "适用：装修/进场施工备案申请与审核。勿与物业报修工单或事件上报混淆。",
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["本人申请填单（选事项） → 提交备案 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "施工区域", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "装修备案审核", "status": "flow"},
            {"name": "装修备案记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "fitout-teal", "label": "装修备案青绿"},
            {"id": "fitout-sand", "label": "装修备案暖沙"},
            {"id": "fitout-slate", "label": "装修备案灰青"},
            {"id": "fitout-night", "label": "装修备案深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="施工区域",
            flow_feature="装修备案审核",
            records_feature="装修备案记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "fitout_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "fitout_site",
        },
    },
    "DOM-ACAD": {
        "label": "学籍异动",
        # 词表只做硬分流；长尾说法交给 match_recommend
        "keywords": ["学籍异动", "转专业申请", "缓考申请", "休学申请", "复学申请", "学籍变更"],
        "match_hint": "适用：转专业/缓考/休学复学等学籍异动申请审核。勿与成绩更正、选课占名额或请假混淆。",
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["本人申请填单（选事项） → 提交申请 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "异动事项", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "异动申请审核", "status": "flow"},
            {"name": "异动申请记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "acad-teal", "label": "学籍异动青绿"},
            {"id": "acad-sand", "label": "学籍异动暖沙"},
            {"id": "acad-slate", "label": "学籍异动灰青"},
            {"id": "acad-night", "label": "学籍异动深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="异动事项",
            flow_feature="异动申请审核",
            records_feature="异动申请记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "acad_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "acad_matter",
        },
    },
    "DOM-TRIP": {
        "label": "出差加班",
        # 词表只做硬分流；长尾说法交给 match_recommend
        "keywords": ["出差申请", "加班审批", "出差审批", "加班申请", "公出申请", "加班单"],
        "match_hint": "适用：出差/加班申请与审批销结。勿与请销假（考勤请假）、用车申请或旅行社线路报名混淆。",
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["本人申请填单（选事项） → 提交申请 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "事项类型", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "出差加班单审核", "status": "flow"},
            {"name": "出差加班单记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "trip-teal", "label": "出差加班青绿"},
            {"id": "trip-sand", "label": "出差加班暖沙"},
            {"id": "trip-slate", "label": "出差加班灰青"},
            {"id": "trip-night", "label": "出差加班深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="事项类型",
            flow_feature="出差加班单审核",
            records_feature="出差加班单记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "trip_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "trip_matter",
        },
    },
    "DOM-EXPENSE": {
        "label": "经费报销",
        # 词表只做硬分流；长尾说法交给 match_recommend
        "keywords": ["经费报销", "报销申请", "费用报销", "差旅报销", "报销审批", "报销单"],
        "match_hint": "适用：经费/差旅报销单审核（无银行直连）。勿与学生资助、用章或开具证明混淆。",
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["本人申请填单（选事项） → 提交报销 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "经费项目", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "报销单审核", "status": "flow"},
            {"name": "报销单记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "expense-teal", "label": "经费报销青绿"},
            {"id": "expense-sand", "label": "经费报销暖沙"},
            {"id": "expense-slate", "label": "经费报销灰青"},
            {"id": "expense-night", "label": "经费报销深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="经费项目",
            flow_feature="报销单审核",
            records_feature="报销单记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "expense_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "expense_project",
        },
    },
}
