"""领域目录 — 学工预设（P-12～P-16）。"""

from __future__ import annotations

from app.bake.gate_contracts import gate_archive_ticket

DOMAINS: dict = {
    "DOM-CREDIT": {
        "label": "第二课堂认定",
        "keywords": [
            "第二课堂",
            "学分认定",
            "第二课堂学分",
            "素拓学分",
            "素质拓展认定",
            "第二课堂认定",
            "课外学分认定",
            "学分认证",
            "素质学分",
            "素拓项目",
        ],
        "match_hint": (
            "适用：第二课堂/素拓学分项目建档与认定申请审核。"
            "勿与公选课选课占名额（选课）、活动报名、成绩更正或综测德育分混淆。"
        ),
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["选档案事项 → 提交认定 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "认定项目", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "学分认定审核", "status": "flow"},
            {"name": "学分认定记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "credit-teal", "label": "第二课堂认定青绿"},
            {"id": "credit-sand", "label": "第二课堂认定暖沙"},
            {"id": "credit-slate", "label": "第二课堂认定灰青"},
            {"id": "credit-night", "label": "第二课堂认定深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="认定项目",
            flow_feature="学分认定审核",
            records_feature="学分认定记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "credit_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "credit_item",
        },
    },
    "DOM-LABOR": {
        "label": "劳动时长认定",
        "keywords": [
            "劳动教育",
            "志愿时长",
            "劳动时长",
            "劳动时长认定",
            "志愿时长认定",
            "劳动教育认定",
            "实践时长认定",
            "劳动实践认定",
            "工时认定",
            "工时认定与核销",
            "义务劳动",
        ],
        "match_hint": (
            "适用：劳动教育/志愿实践时长登记与认定审核（对着劳动项目提交认定单）。"
            "勿与时间银行账户余额存取核销（时间银行）、志愿活动报名占名额、请假考勤或第二课堂学分认定混淆。"
        ),
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["选档案事项 → 提交时长 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "劳动项目", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "时长认定审核", "status": "flow"},
            {"name": "时长认定记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "labor-teal", "label": "劳动时长认定青绿"},
            {"id": "labor-sand", "label": "劳动时长认定暖沙"},
            {"id": "labor-slate", "label": "劳动时长认定灰青"},
            {"id": "labor-night", "label": "劳动时长认定深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="劳动项目",
            flow_feature="时长认定审核",
            records_feature="时长认定记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "labor_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "labor_item",
        },
    },
    "DOM-EVAL": {
        "label": "网上评教",
        "keywords": [
            "网上评教",
            "教学评价",
            "评教系统",
            "课程评价",
            "学生评教",
            "学期评教",
            "教师评价",
            "教学质量评价",
            "打分评语",
        ],
        "match_hint": (
            "适用：学期末对课程/教师提交多维评分与评语（教学内容/态度/收获，可选匿名）。"
            "勿与成绩更正/成绩排名、论坛发帖、满意度问卷或综测申报混淆。"
        ),
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["选课程 → 多维评分与评语 → 提交完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "评教课程", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "提交评教", "status": "flow"},
            {"name": "评教记录", "status": "module"},
            {"name": "多维评分与评语", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": ["可配置问卷引擎", "真匿名密码学"],
        "themes": [
            {"id": "eval-teal", "label": "网上评教青绿"},
            {"id": "eval-sand", "label": "网上评教暖沙"},
            {"id": "eval-slate", "label": "网上评教灰青"},
            {"id": "eval-night", "label": "网上评教深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="评教课程",
            flow_feature="提交评教",
            records_feature="评教记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "eval_sheet",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "eval_course",
        },
    },
    "DOM-MORAL": {
        "label": "综测申报",
        "keywords": [
            "综测",
            "综合测评",
            "德育分",
            "综测申报",
            "加减分申报",
            "综合测评系统",
            "德育分申报",
            "素质测评",
            "品德量化",
            "加减分材料",
        ],
        "match_hint": (
            "适用：综合测评/德育分指标项与加减分申报审核台账。"
            "勿与成绩更正/课程成绩排名、资助申请或第二课堂学分认定混淆——"
            "加减分申报≠教务成绩台账。"
        ),
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["选档案事项 → 提交申报 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "测评指标", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "加减分申请审核", "status": "flow"},
            {"name": "加减分申请记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "moral-teal", "label": "综测申报青绿"},
            {"id": "moral-sand", "label": "综测申报暖沙"},
            {"id": "moral-slate", "label": "综测申报灰青"},
            {"id": "moral-night", "label": "综测申报深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="测评指标",
            flow_feature="加减分申请审核",
            records_feature="加减分申请记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "moral_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "moral_item",
        },
    },
    "DOM-AWARD": {
        "label": "成果登记",
        "keywords": [
            "创新学分",
            "竞赛获奖登记",
            "获奖登记",
            "学科竞赛登记",
            "创新学分登记",
            "竞赛成果登记",
            "科研成果登记",
            "获奖备案",
            "成果备案",
        ],
        "match_hint": (
            "适用：创新学分/竞赛获奖/成果登记与审核台账。"
            "勿与学生资助/奖学金评定、成绩更正或活动报名混淆。"
        ),
        "entities": ["Archive", "Category", "Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["选档案事项 → 提交登记 → 审批完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "成果类型", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "成果登记审核", "status": "flow"},
            {"name": "成果登记记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "award-teal", "label": "成果登记青绿"},
            {"id": "award-sand", "label": "成果登记暖沙"},
            {"id": "award-slate", "label": "成果登记灰青"},
            {"id": "award-night", "label": "成果登记深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="成果类型",
            flow_feature="成果登记审核",
            records_feature="成果登记记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "award_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "award_item",
        },
    },
}
