"""领域目录：ARCHETYPES / DOMAIN_CAPABILITIES / DOMAINS。门禁见 gate_contracts。"""

from __future__ import annotations

from app.bake.gate_contracts import gate_archive_ticket, gate_library, gate_standalone_ticket

ARCHETYPES = {
    "ARCH-CRUD": {"label": "纯管理", "keywords": ["管理", "信息维护", "增删改查"]},
    "ARCH-FLOW": {"label": "审核流", "keywords": ["审核", "审批", "借阅", "报修", "申请"]},
    "ARCH-TRADE": {"label": "交易流", "keywords": ["交易", "二手", "订单", "支付", "购物"]},
    "ARCH-RESERVE": {"label": "预约流", "keywords": ["预约", "挂号", "车位", "订座"]},
    "ARCH-CONTENT": {
        "label": "内容流",
        "keywords": [
            "资讯", "新闻", "文章", "发布", "影视", "视频", "点播", "音乐", "歌曲",
            "论坛", "博客", "帖子", "BBS", "贴吧", "CMS",
        ],
    },
    "ARCH-STOCK": {"label": "进销存", "keywords": ["进销存", "库存", "采购", "出库"]},
}


# domain → 默认所需能力（题目无关的积木组合）
# 分组见 HANDOFF「90% 毕设覆盖」
DOMAIN_CAPABILITIES: dict[str, list[str]] = {
    # A 借用/占用
    "DOM-LIBRARY": ["archive", "ticket_flow", "quota", "deadline", "content", "org_users", "recommend"],
    "DOM-EQUIP": ["archive", "ticket_flow", "quota", "deadline", "content", "org_users", "recommend"],
    "DOM-ASSET": ["archive", "ticket_flow", "quota", "content", "org_users"],
    # B 报修/工单
    "DOM-DORM": ["ticket_flow", "content", "org_users"],
    "DOM-PROPERTY": ["ticket_flow", "content", "org_users"],
    "DOM-IT": ["ticket_flow", "content", "org_users"],
    # C 报名/申请
    "DOM-ACTIVITY": ["archive", "ticket_flow", "quota", "content", "org_users"],
    "DOM-LOST": ["archive", "ticket_flow", "content", "org_users"],
    "DOM-COURSE": ["archive", "ticket_flow", "quota", "content", "org_users"],
    # D 交易（缺 order_lines → reject）
    "DOM-SHOP": ["archive", "order_lines", "quota", "content", "org_users"],
    "DOM-FOOD": ["archive", "order_lines", "quota", "content", "org_users"],
    # E 预约（缺 slot_reserve → reject）
    "DOM-HOSPITAL": ["archive", "slot_reserve", "content", "org_users"],
    "DOM-PARKING": ["slot_reserve", "ticket_flow", "deadline", "content", "org_users"],
    "DOM-MEETING": ["slot_reserve", "ticket_flow", "content", "org_users"],
    "DOM-SALON": ["slot_reserve", "archive", "content", "org_users"],
    "DOM-HOTEL": ["slot_reserve", "order_lines", "archive", "content", "org_users"],
    # F 兜底
    "DOM-GENERIC": ["archive", "content", "org_users"],
    # G 内容/媒资/社区
    "DOM-MEDIA": ["archive", "ticket_flow", "content", "org_users", "recommend"],
    "DOM-MUSIC": ["archive", "ticket_flow", "content", "org_users", "recommend"],
    "DOM-FORUM": ["archive", "ticket_flow", "content", "org_users", "recommend"],
    "DOM-BLOG": ["archive", "ticket_flow", "content", "org_users", "recommend"],
}


DOMAINS = {
    "DOM-LIBRARY": {
        "label": "图书",
        "keywords": ["图书", "借阅", "图书馆", "读者"],
        "entities": ["Book", "Category", "Borrow", "Notice"],
        "roles": ["reader", "admin"],
        "flows": ["申请借阅 → 审核 → 归还", "逾期提醒 → 归还 / 罚款登记"],
        "features": [
            {"name": "读者注册 / 登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "图书检索与详情", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "读者管理", "status": "module"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "借阅申请 → 审核", "status": "flow"},
            {"name": "借阅记录", "status": "module"},
            {"name": "归还 / 逾期", "status": "flow"},
            {"name": "逾期提醒与罚款", "status": "flow"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "人脸识别进馆", "status": "out_of_mvp"},
            {"name": "协同过滤推荐", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["人脸识别", "协同过滤推荐"],
        "themes": [
            {"id": "lib-ink", "label": "墨蓝书香"},
            {"id": "lib-grove", "label": "青松阅览"},
            {"id": "lib-amber", "label": "暖光自习"},
            {"id": "lib-plum", "label": "梅影典藏"},
            {"id": "lib-slate", "label": "石青检索"},
            {"id": "lib-night", "label": "夜读静谧"},
        ],
        "gate": gate_library(),
        "portal_banners": True,
    },
    "DOM-EQUIP": {
        "label": "设备借用",
        "keywords": ["设备借用", "器材", "实验室设备", "物资借用"],
        "entities": ["Equip", "Category", "Loan", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["申请借用 → 审核 → 归还"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "设备检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "借用申请 → 审核", "status": "flow"},
            {"name": "借用记录", "status": "module"},
            {"name": "归还 / 逾期", "status": "flow"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "硬件交付（开题提及）", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["硬件交付"],
        "themes": [
            {"id": "equip-steel", "label": "器械钢蓝"},
            {"id": "equip-amber", "label": "警示琥珀"},
            {"id": "equip-mint", "label": "实验青绿"},
            {"id": "equip-night", "label": "夜间库房"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="设备检索",
            flow_feature="借用申请 → 审核",
            records_feature="借用记录",
            users_feature="用户管理",
            category_feature="分类管理",
            overdue_feature="归还 / 逾期",
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "loan",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "equip",
        },
    },
    "DOM-ASSET": {
        "label": "物资领用",
        "keywords": ["固定资产", "耗材申领", "物资领用", "仓库领用"],
        "entities": ["Asset", "Category", "Requisition", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["提交申领 → 审核 → 出库"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "物资目录", "status": "domain"},
            {"name": "申领审核", "status": "flow"},
            {"name": "公告", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "asset-olive", "label": "仓储橄榄"},
            {"id": "asset-clay", "label": "库房暖陶"},
            {"id": "asset-slate", "label": "台账灰青"},
            {"id": "asset-night", "label": "盘点深色"},
        ],
    },
    "DOM-SHOP": {
        "label": "商城",
        "keywords": ["商城", "商品", "购物车", "下单"],
        "entities": ["Product", "Category", "Order", "Cart"],
        "roles": ["user", "admin"],
        "flows": ["加购 → 下单 → 发货"],
        "features": [
            {"name": "用户登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "商品浏览", "status": "domain"},
            {"name": "购物车下单", "status": "flow"},
            {"name": "订单管理", "status": "flow"},
            {"name": "推荐算法", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["推荐算法"],
        "themes": [
            {"id": "shop-coral", "label": "促销珊瑚"},
            {"id": "shop-ocean", "label": "清仓海蓝"},
            {"id": "shop-lime", "label": "生鲜青绿"},
            {"id": "shop-gold", "label": "会员金"},
            {"id": "shop-night", "label": "夜间闪购"},
        ],
    },
    "DOM-DORM": {
        "label": "宿舍",
        "keywords": ["宿舍", "报修", "寝室", "水电"],
        "entities": ["Dorm", "Repair", "Notice"],
        "roles": ["student", "admin"],
        "flows": ["提交报修 → 受理 → 完成"],
        "features": [
            {"name": "学生登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "楼栋房间管理", "status": "module"},
            {"name": "报修类型管理", "status": "module"},
            {"name": "学生管理", "status": "module"},
            {"name": "报修申请 → 受理", "status": "flow"},
            {"name": "报修记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "人脸门禁", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["人脸门禁"],
        "themes": [
            {"id": "dorm-sky", "label": "宿舍天蓝"},
            {"id": "dorm-orange", "label": "维修橙"},
            {"id": "dorm-leaf", "label": "生活绿"},
            {"id": "dorm-violet", "label": "寝室紫雾"},
            {"id": "dorm-night", "label": "熄灯模式"},
        ],
        "gate": gate_standalone_ticket(
            flow_feature="报修申请 → 受理",
            records_feature="报修记录",
            users_feature="学生管理",
            site_feature="楼栋房间管理",
            type_feature="报修类型管理",
        ),
        "runtime": {
            "ticket_mode": "standalone",
            "ticket_table": "repair",
            "register_role": "student",
            "lookup_site_table": "dorm_building",
            "lookup_unit_table": "dorm_room",
            "lookup_type_table": "repair_type",
            "lookup_site_label": "楼栋",
            "lookup_unit_label": "房间",
            "lookup_type_label": "报修类型",
        },
    },
    "DOM-PROPERTY": {
        "label": "物业报修",
        "keywords": ["物业", "社区报修", "维修工单", "小区报修"],
        "entities": ["Ticket", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["提交报修 → 受理 → 完成"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "楼栋房间管理", "status": "module"},
            {"name": "报修类型管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "报修申请 → 受理", "status": "flow"},
            {"name": "报修记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "prop-teal", "label": "物业青绿"},
            {"id": "prop-sand", "label": "社区暖沙"},
            {"id": "prop-ink", "label": "工单墨蓝"},
            {"id": "prop-night", "label": "夜间值班"},
        ],
        "gate": gate_standalone_ticket(
            flow_feature="报修申请 → 受理",
            records_feature="报修记录",
            users_feature="用户管理",
            site_feature="楼栋房间管理",
            type_feature="报修类型管理",
        ),
        "runtime": {
            "ticket_mode": "standalone",
            "ticket_table": "ticket",
            "register_role": "user",
            "lookup_site_table": "building",
            "lookup_unit_table": "room",
            "lookup_type_table": "ticket_type",
            "lookup_site_label": "楼栋",
            "lookup_unit_label": "房间",
            "lookup_type_label": "报修类型",
        },
    },
    "DOM-IT": {
        "label": "IT 报修",
        "keywords": ["校园网", "网络报修", "IT运维", "机房报修"],
        "entities": ["Ticket", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["提交故障 → 受理 → 完成"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "区域终端管理", "status": "module"},
            {"name": "故障类型管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "故障报修 → 受理", "status": "flow"},
            {"name": "报修记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "it-cyan", "label": "运维青"},
            {"id": "it-violet", "label": "机房紫"},
            {"id": "it-lime", "label": "终端绿"},
            {"id": "it-night", "label": "机房夜色"},
        ],
        "gate": gate_standalone_ticket(
            flow_feature="故障报修 → 受理",
            records_feature="报修记录",
            users_feature="用户管理",
            site_feature="区域终端管理",
            type_feature="故障类型管理",
        ),
        "runtime": {
            "ticket_mode": "standalone",
            "ticket_table": "ticket",
            "register_role": "user",
            "lookup_site_table": "campus_zone",
            "lookup_unit_table": "endpoint",
            "lookup_type_table": "fault_type",
            "lookup_site_label": "区域",
            "lookup_unit_label": "终端点",
            "lookup_type_label": "故障类型",
        },
    },
    "DOM-ACTIVITY": {
        "label": "活动报名",
        "keywords": ["社团活动", "志愿活动", "活动报名", "讲座报名"],
        "entities": ["Activity", "Signup", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["报名 → 审核 → 参加"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "活动浏览", "status": "domain"},
            {"name": "报名审核", "status": "flow"},
            {"name": "公告", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "act-coral", "label": "活动珊瑚"},
            {"id": "act-sky", "label": "报名天蓝"},
            {"id": "act-lime", "label": "志愿青绿"},
            {"id": "act-night", "label": "晚会夜色"},
        ],
    },
    "DOM-LOST": {
        "label": "失物招领",
        "keywords": ["失物招领", "失物", "招领"],
        "entities": ["Item", "Claim", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["登记 → 认领申请 → 审核"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "失物浏览", "status": "domain"},
            {"name": "认领审核", "status": "flow"},
            {"name": "公告", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "lost-amber", "label": "招领暖黄"},
            {"id": "lost-blue", "label": "寻物蓝"},
            {"id": "lost-gray", "label": "登记灰"},
            {"id": "lost-night", "label": "夜间公示"},
        ],
    },
    "DOM-COURSE": {
        "label": "选课",
        "keywords": ["选课", "公选课", "课程报名", "学分"],
        "entities": ["Course", "Enrollment", "Notice"],
        "roles": ["student", "admin"],
        "flows": ["选课申请 → 审核/占名额"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "课程浏览", "status": "domain"},
            {"name": "选课与名额", "status": "flow"},
            {"name": "公告", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "course-ink", "label": "课表墨蓝"},
            {"id": "course-grove", "label": "学期青绿"},
            {"id": "course-clay", "label": "教室暖陶"},
            {"id": "course-night", "label": "夜修模式"},
        ],
    },
    "DOM-FOOD": {
        "label": "点餐",
        "keywords": ["点餐", "食堂", "外卖", "菜品"],
        "entities": ["Dish", "Order", "Category"],
        "roles": ["user", "admin"],
        "flows": ["选菜 → 下单 → 取餐"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "菜品浏览", "status": "domain"},
            {"name": "下单取餐", "status": "flow"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "food-chili", "label": "食堂红"},
            {"id": "food-bamboo", "label": "清新竹绿"},
            {"id": "food-sesame", "label": "暖米褐"},
            {"id": "food-berry", "label": "果饮紫"},
            {"id": "food-night", "label": "夜宵档"},
        ],
    },
    "DOM-HOSPITAL": {
        "label": "医院",
        "keywords": ["医院", "挂号", "就诊", "门诊"],
        "entities": ["Doctor", "Department", "Appointment"],
        "roles": ["patient", "admin"],
        "flows": ["选科室 → 挂号 → 就诊"],
        "features": [
            {"name": "患者登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "挂号预约", "status": "flow"},
            {"name": "科室医生", "status": "domain"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "hosp-blue", "label": "医护蓝"},
            {"id": "hosp-mint", "label": "洁净绿"},
            {"id": "hosp-coral", "label": "分诊醒目"},
            {"id": "hosp-sky", "label": "候诊淡青"},
            {"id": "hosp-night", "label": "值班深色"},
        ],
    },
    "DOM-PARKING": {
        "label": "车位",
        "keywords": ["车位", "停车", "预约车位"],
        "entities": ["ParkingLot", "Space", "Reservation"],
        "roles": ["user", "admin"],
        "flows": ["选车位 → 预约 → 入场"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "车位预约", "status": "flow"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "park-asphalt", "label": "车位灰蓝"},
            {"id": "park-signal", "label": "通行绿"},
            {"id": "park-amber", "label": "警示黄"},
            {"id": "park-cyan", "label": "导航青"},
            {"id": "park-night", "label": "地库夜色"},
        ],
    },
    "DOM-MEETING": {
        "label": "会议室",
        "keywords": ["会议室", "会议室预约", "场地预约"],
        "entities": ["Room", "Reservation"],
        "roles": ["user", "admin"],
        "flows": ["选会议室 → 预约 → 取消/完成"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "会议室预约", "status": "flow"},
            {"name": "公告", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "meet-blue", "label": "会议蓝"},
            {"id": "meet-gray", "label": "洽谈灰"},
            {"id": "meet-green", "label": "空闲绿"},
            {"id": "meet-night", "label": "夜间预约"},
        ],
    },
    "DOM-SALON": {
        "label": "服务预约",
        "keywords": ["美发", "美容预约", "理发预约", "服务预约"],
        "entities": ["Service", "Slot", "Booking"],
        "roles": ["user", "admin"],
        "flows": ["选服务 → 预约时段"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "服务与预约", "status": "flow"},
            {"name": "公告", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "salon-rose", "label": "护理玫瑰"},
            {"id": "salon-cream", "label": "沙龙暖米"},
            {"id": "salon-ink", "label": "造型墨"},
            {"id": "salon-night", "label": "夜场预约"},
        ],
    },
    "DOM-HOTEL": {
        "label": "客房",
        "keywords": ["宾馆", "客房", "酒店预订", "住宿预订"],
        "entities": ["Room", "Booking", "Order"],
        "roles": ["user", "admin"],
        "flows": ["选房 → 预订 → 入住/离店"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "房型浏览", "status": "domain"},
            {"name": "预订订单", "status": "flow"},
            {"name": "公告", "status": "module"},
            {"name": "真支付对接", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["真支付对接"],
        "themes": [
            {"id": "hotel-gold", "label": "酒店金"},
            {"id": "hotel-navy", "label": "客房藏蓝"},
            {"id": "hotel-sand", "label": "大堂暖沙"},
            {"id": "hotel-night", "label": "夜宿深色"},
        ],
    },
    "DOM-MEDIA": {
        "label": "影视综",
        "keywords": ["影视", "电影", "电视剧", "综艺", "视频点播", "在线视频", "片库"],
        "entities": ["Media", "Category", "Favorite", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["浏览片单 → 播放 → 收藏"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "片单检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "收藏 / 想看", "status": "flow"},
            {"name": "收藏记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "协同过滤推荐", "status": "out_of_mvp"},
            {"name": "直播与弹幕", "status": "out_of_mvp"},
            {"name": "转码 CDN", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["协同过滤推荐", "直播与弹幕", "转码 CDN"],
        "themes": [
            {"id": "media-cinema", "label": "影院午夜"},
            {"id": "media-amber", "label": "暖幕琥珀"},
            {"id": "media-teal", "label": "荧幕青绿"},
            {"id": "media-night", "label": "观影深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="片单检索",
            flow_feature="收藏 / 想看",
            records_feature="收藏记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "favorite",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "media",
        },
    },
    "DOM-MUSIC": {
        "label": "音乐",
        "keywords": ["音乐", "歌曲", "歌单", "在线音乐", "音乐播放器", "听歌", "曲库"],
        "entities": ["Track", "Category", "Favorite", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["浏览曲库 → 播放 → 收藏"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "曲库检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "收藏 / 喜欢", "status": "flow"},
            {"name": "收藏记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "协同过滤推荐", "status": "out_of_mvp"},
            {"name": "歌词同步", "status": "out_of_mvp"},
            {"name": "真转码 CDN", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["协同过滤推荐", "歌词同步", "真转码 CDN"],
        "themes": [
            {"id": "music-vinyl", "label": "黑胶午夜"},
            {"id": "music-amber", "label": "暖光耳机"},
            {"id": "music-teal", "label": "波形青绿"},
            {"id": "music-night", "label": "夜听深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="曲库检索",
            flow_feature="收藏 / 喜欢",
            records_feature="收藏记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "favorite",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "track",
        },
    },
    "DOM-FORUM": {
        "label": "论坛",
        "keywords": ["论坛", "BBS", "贴吧", "社区帖子", "板块", "发帖", "回帖", "楼中楼"],
        "entities": ["Post", "Category", "Reply", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["浏览主帖 → 回复 → 版主审核展示"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "帖子检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "回复 / 楼中楼", "status": "flow"},
            {"name": "回复记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "实时私信", "status": "out_of_mvp"},
            {"name": "用户自由开新主帖无审核", "status": "out_of_mvp"},
            {"name": "无限深度树形嵌套引擎", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["实时私信", "用户自由开新主帖无审核", "无限深度树形嵌套引擎"],
        "themes": [
            {"id": "forum-ink", "label": "论坛墨蓝"},
            {"id": "forum-amber", "label": "暖帖琥珀"},
            {"id": "forum-teal", "label": "版块青绿"},
            {"id": "forum-night", "label": "夜读深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="帖子检索",
            flow_feature="回复 / 楼中楼",
            records_feature="回复记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "reply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "post",
        },
    },
    "DOM-BLOG": {
        "label": "博客",
        "keywords": ["博客", "个人博客", "文章系统", "资讯发布", "CMS", "博文"],
        "entities": ["Article", "Category", "Favorite", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["浏览文章 → 收藏 → 编辑确认"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "文章检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "收藏 / 订阅", "status": "flow"},
            {"name": "收藏记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "富文本协同编辑", "status": "out_of_mvp"},
            {"name": "多作者工作流引擎", "status": "out_of_mvp"},
            {"name": "SEO / CDN 分发", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["富文本协同编辑", "多作者工作流引擎", "SEO / CDN 分发"],
        "themes": [
            {"id": "blog-ink", "label": "博文墨蓝"},
            {"id": "blog-grove", "label": "随笔青绿"},
            {"id": "blog-clay", "label": "暖陶阅读"},
            {"id": "blog-night", "label": "夜读深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="文章检索",
            flow_feature="收藏 / 订阅",
            records_feature="收藏记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "favorite",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "article",
        },
    },
    "DOM-GENERIC": {
        "label": "通用",
        "keywords": [],
        "entities": ["Item", "Category", "Notice"],
        "roles": ["user", "admin"],
        "flows": ["新增 → 编辑 → 查询"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "基础 CRUD", "status": "domain"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "gen-ink", "label": "通用墨蓝"},
            {"id": "gen-grove", "label": "通用青绿"},
            {"id": "gen-clay", "label": "通用暖陶"},
            {"id": "gen-night", "label": "通用深色"},
        ],
    },
}
