"""领域目录：ARCHETYPES / DOMAIN_CAPABILITIES / DOMAINS。门禁见 gate_contracts。"""

from __future__ import annotations

from app.bake.gate_contracts import (
    gate_archive_favorites,
    gate_archive_ticket,
    gate_order_shell,
    gate_slot_shell,
    gate_standalone_ticket,
)

# 行为词桶（有上限）：对齐运行时积木，不堆行业名词。新增词先问「是不是新能力」。
# 同分/并集排序：预约 > 交易 > 审核流（catalog 与 archetype_shells 共用）
ARCH_PATH_ORDER: tuple[str, ...] = (
    "ARCH-RESERVE",
    "ARCH-TRADE",
    "ARCH-FLOW",
    "ARCH-STOCK",
    "ARCH-CONTENT",
    "ARCH-CRUD",
)

ARCHETYPES = {
    # 不用光杆「管理」：开题几乎都带「管理系统」，会压过预约/订单等更具体原型
    "ARCH-CRUD": {"label": "纯管理", "keywords": ["信息维护", "增删改查", "档案管理", "台账管理"]},
    "ARCH-FLOW": {
        "label": "审核流",
        "keywords": [
            # 审核 / 单据
            "审核", "审批", "会签", "申请", "申报", "递交", "认定",
            "借阅", "借还", "报修", "保修", "维修", "工单", "派发", "派单", "回访", "投诉", "挂失",
            "申领", "领用", "巡检", "巡查", "报名", "请假",
            "跟进", "线索",
            # 流转类 = ticket_flow 同义，不新开 ARCH
            "流转", "上报", "分拨", "转办",
            # 事件/公卫（与 DOM-EVENT 对齐；勿用光杆「打卡/照护」抬分）
            "随访", "排查", "晨检", "晨午检", "监测", "处置", "密接", "接触者", "病例",
            "健康监测", "健康打卡", "复工监测", "隔离观察", "健康筛查",
            # 英文行为（极少）
            "repair", "approval", "workflow",
        ],
    },
    "ARCH-TRADE": {
        "label": "交易流",
        "keywords": [
            "交易", "二手", "订单", "下单", "支付", "购物", "购物车", "交换",
            "配送", "助餐", "拼单", "预售", "核销", "点单", "订餐", "代购", "接单",
            "结算", "团购", "转卖", "提货", "成交", "拍卖", "跑腿", "售票", "点餐",
            "销售", "电商", "直销",
            "order", "checkout", "cart",
        ],
    },
    "ARCH-RESERVE": {
        "label": "预约流",
        "keywords": [
            "预约", "预订", "挂号", "车位", "订座", "排班", "场次", "占座", "座位确认",
            "座位管理", "座位预约", "包厢预约", "改约", "订场", "占坑", "泊车",
            "booking", "reservation",
        ],
    },
    "ARCH-CONTENT": {
        "label": "内容流",
        "keywords": [
            # 不用光杆「发布」：公告发布几乎每题都有，会误抬内容流
            "资讯", "新闻", "文章", "影视", "视频", "点播", "音乐", "歌曲",
            "论坛", "博客", "帖子", "BBS", "贴吧", "CMS", "展播", "收藏",
        ],
    },
    "ARCH-STOCK": {
        "label": "进销存",
        "keywords": [
            "进销存", "库存", "采购", "出库", "入库", "盘点", "inventory",
            "仓储", "调拨", "库存预警", "出入库", "物资调度",
        ],
    },
}


# domain → 默认所需能力（题目无关的积木组合）
# 分组见 HANDOFF「90% 毕设覆盖」
DOMAIN_CAPABILITIES: dict[str, list[str]] = {
    # A 借用/占用
    "DOM-LIBRARY": ["archive", "ticket_flow", "quota", "deadline", "content", "org_users", "recommend"],
    "DOM-EQUIP": ["archive", "ticket_flow", "quota", "deadline", "content", "org_users", "recommend"],
    "DOM-ASSET": ["archive", "ticket_flow", "quota", "content", "org_users"],
    "DOM-CRM": ["archive", "ticket_flow", "content", "org_users"],
    "DOM-EVENT": ["archive", "ticket_flow", "archive_log", "content", "org_users"],
    "DOM-ATTEND": ["archive", "ticket_flow", "content", "org_users"],
    "DOM-RECRUIT": ["archive", "ticket_flow", "content", "org_users"],
    "DOM-GRADE": ["archive", "ticket_flow", "content", "org_users"],
    "DOM-INTERN": ["archive", "ticket_flow", "content", "org_users"],
    "DOM-PARCEL": ["archive", "ticket_flow", "quota", "content", "org_users"],
    # B 报修/工单
    "DOM-DORM": ["ticket_flow", "content", "org_users"],
    "DOM-PROPERTY": ["ticket_flow", "content", "org_users"],
    "DOM-IT": ["ticket_flow", "content", "org_users"],
    # C 报名/申请
    "DOM-ACTIVITY": ["archive", "ticket_flow", "quota", "content", "org_users", "time_conflict"],
    "DOM-LOST": ["archive", "ticket_flow", "quota", "content", "org_users"],
    "DOM-COURSE": ["archive", "ticket_flow", "quota", "content", "org_users", "time_conflict"],
    # D 交易（order_lines）
    "DOM-SHOP": ["archive", "order_lines", "quota", "content", "org_users", "guestbook"],
    "DOM-FOOD": ["archive", "order_lines", "quota", "content", "org_users", "guestbook"],
    # E 预约（slot_reserve；资源走 archive）
    "DOM-HOSPITAL": ["archive", "slot_reserve", "content", "org_users"],
    "DOM-PARKING": ["archive", "slot_reserve", "content", "org_users"],
    "DOM-MEETING": ["archive", "slot_reserve", "content", "org_users"],
    "DOM-SALON": ["archive", "slot_reserve", "content", "org_users"],
    "DOM-HOTEL": ["archive", "slot_reserve", "order_lines", "content", "org_users"],
    # F 兜底
    "DOM-GENERIC": ["archive", "content", "org_users"],
    # G 内容/媒资/社区（MEDIA/MUSIC/BLOG 即时收藏；FORUM 回帖仍走审核单）
    "DOM-MEDIA": ["archive", "favorites", "content", "org_users", "recommend"],
    "DOM-MUSIC": ["archive", "favorites", "content", "org_users", "recommend"],
    "DOM-FORUM": ["archive", "ticket_flow", "content", "org_users", "recommend"],
    "DOM-BLOG": ["archive", "favorites", "content", "org_users", "recommend"],
}


# out_of_mvp：行业壳「常见边界」示例外壳，可随时改本表；交付清单由
# attach_accept → compose_out_of_mvp（目录相关项 ∪ 开题扫词）合成，非写死契约。
DOMAINS = {
    "DOM-LIBRARY": {
        "label": "图书",
        "keywords": ["图书", "借阅", "图书馆", "读者"],
        "match_hint": "适用：图书借阅、读者借还审核。勿与设备借用（器材/实验室）或选课混淆。",
        "entities": ["Book", "Category", "Borrow", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["申请借阅 → 审核 → 归还", "逾期提醒 → 归还 / 罚款登记"],
        "features": [
            {"name": "读者注册 / 登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "图书检索与详情", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "读者管理", "status": "module"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "借阅申请 → 审核", "status": "flow"},
            {"name": "自选应还日 / 申请数量", "status": "flow"},
            {"name": "借阅记录", "status": "module"},
            {"name": "归还 / 逾期", "status": "flow"},
            {"name": "逾期提醒与罚款", "status": "flow"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "人脸识别进馆", "status": "out_of_mvp"},
            {"name": "协同过滤推荐", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["人脸识别", "协同过滤推荐"],
        "themes": [
            {"id": "lib-ink", "label": "墨蓝书香"},
            {"id": "lib-grove", "label": "青松阅览"},
            {"id": "lib-amber", "label": "暖光自习"},
            {"id": "lib-plum", "label": "梅影典藏"},
            {"id": "lib-slate", "label": "石青检索"},
            {"id": "lib-night", "label": "夜读静谧"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="图书检索与详情",
            flow_feature="借阅申请 → 审核",
            records_feature="借阅记录",
            users_feature="读者管理",
            category_feature="分类管理",
            overdue_feature="逾期提醒与罚款",
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "borrow",
            "register_role": "reader",
            "archive_category_table": "category",
            "archive_item_table": "book",
        },
    },
    "DOM-EQUIP": {
        "label": "设备借用",
        "keywords": ["设备借用", "器材", "实验室设备", "物资借用", "实验室管理"],
        "match_hint": "适用：实验室/器材借用归还审核。勿与物资领用（耗材出库）或图书借阅混淆。",
        "entities": ["Equip", "Category", "Loan", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["申请借用 → 审核 → 归还"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "设备检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "借用申请 → 审核", "status": "flow"},
            {"name": "自选应还日 / 申请数量", "status": "flow"},
            {"name": "借用记录", "status": "module"},
            {"name": "归还 / 逾期", "status": "flow"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "硬件交付（开题提及）", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["硬件交付"],
        "themes": [
            {"id": "equip-steel", "label": "器械钢蓝"},
            {"id": "equip-amber", "label": "警示琥珀"},
            {"id": "equip-mint", "label": "实验青绿"},
            {"id": "equip-night", "label": "夜间库房"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="设备检索",
            flow_feature="借用申请 → 审核",
            records_feature="借用记录",
            users_feature="用户管理",
            category_feature="分类管理",
            overdue_feature="归还 / 逾期",
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "loan",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "equip",
        },
    },
    "DOM-ASSET": {
        "label": "物资领用",
        "keywords": [
            "固定资产",
            "耗材申领",
            "物资申领",
            "仓储物资",
            "物资领用",
            "仓库领用",
            "资产领用",
            "资产台账",
            "办公用品申领",
            "耗材管理",
            "入库出库",
            "出入库",
            "应急物资",
            "物资仓储",
            "仓储调度",
            "物资调度",
            "冷链仓储",
            "冷库",
            "货品台账",
        ],
        "match_hint": (
            "适用：物资/耗材领用、仓储出入库、应急物资调度台账、冷链仓储温湿度台账。"
            "正文顺带提公卫/疫情时，若题名是仓储物资仍选本域，勿改事件上报。"
        ),
        "entities": ["Asset", "Category", "Requisition", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["提交申领 → 审核出库 → 可选退库"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "物资目录", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "申领审核", "status": "flow"},
            {"name": "申领数量", "status": "flow"},
            {"name": "申领记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "RFID/条码全链路盘点", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["RFID/条码全链路盘点"],
        "themes": [
            {"id": "asset-olive", "label": "仓储橄榄"},
            {"id": "asset-clay", "label": "库房暖陶"},
            {"id": "asset-slate", "label": "台账灰青"},
            {"id": "asset-night", "label": "盘点深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="物资目录",
            flow_feature="申领审核",
            records_feature="申领记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "requisition",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "asset",
        },
    },
    "DOM-CRM": {
        "label": "客户跟进",
        "keywords": [
            "CRM",
            "客户关系",
            "客户管理",
            "客户跟进",
            "销售线索",
            "线索管理",
            "客户档案",
        ],
        "match_hint": "适用：客户档案、销售线索跟进审核。勿与事件上报（公卫排查）或通用管理混淆。",
        "entities": ["Customer", "Category", "FollowUp", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["客户建档 → 提交跟进 → 审核完结"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "客户档案", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "客户跟进", "status": "flow"},
            {"name": "跟进记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "外呼中心/公海池", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["外呼中心/公海池"],
        "themes": [
            {"id": "crm-ocean", "label": "客户海蓝"},
            {"id": "crm-slate", "label": "商务灰青"},
            {"id": "crm-sand", "label": "线索暖沙"},
            {"id": "crm-night", "label": "夜访深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="客户档案",
            flow_feature="客户跟进",
            records_feature="跟进记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "follow_up",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "customer",
        },
    },
    "DOM-EVENT": {
        "label": "事件上报",
        # 词表只做硬分流；长尾说法交给 match_recommend（见 match_hint）
        "keywords": [
            "事件上报",
            "公共卫生",
            "公共卫生事件",
            "院感",
            "感染防控",
            "晨检",
            "晨午检",
            "排查",
            "传染病",
            "随访",
            "流调",
            "网格化",
            "健康监测",
            "因病缺课",
            "养老",
            "巡访",
            "献血",
            "健康筛查",
            "食品安全",
            "复工监测",
        ],
        "match_hint": (
            "适用：公卫应急、院感、晨午检、慢性病随访、养老/员工健康监测、网格排查、"
            "食安风险排查、流调协查、献血筛查等「建档+打卡/随访+上报」题。"
            "不适用：门诊挂号（医院）、食堂点餐（点餐）、纯应急物资仓储（物资领用）、"
            "宿舍卫生整改工单（宿舍报修）。"
            "开题主写物资出入库勿选本域。"
        ),
        "entities": ["EventCase", "Category", "EventReport", "ArchiveLog", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["对象建档 → 打卡/随访记录 → 异常上报处置"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "事件档案", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "健康打卡/监测记录", "status": "domain"},
            {"name": "事件上报", "status": "flow"},
            {"name": "上报记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "疾控直报对接", "status": "out_of_mvp"},
            {"name": "物资仓储出入库", "status": "out_of_mvp"},
            {"name": "完整电子量表引擎", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["疾控直报对接", "物资仓储出入库", "完整电子量表引擎"],
        "themes": [
            {"id": "event-teal", "label": "应急青绿"},
            {"id": "event-amber", "label": "警示琥珀"},
            {"id": "event-slate", "label": "台账灰青"},
            {"id": "event-night", "label": "值班深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="事件档案",
            flow_feature="事件上报",
            records_feature="上报记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "event_report",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "event_case",
        },
    },
    "DOM-ATTEND": {
        "label": "考勤请假",
        "keywords": [
            "请假", "销假", "考勤请假", "请假管理", "请假审批", "请假系统",
            "请假申请", "请销假", "事假", "病假", "假勤", "出勤管理",
            "学生请假", "员工请假",
        ],
        "match_hint": (
            "适用：员工/学生请假申请与审批、销假、假勤台账。"
            "勿与公卫健康打卡/晨午检（事件上报）或宿舍卫生整改混淆。"
        ),
        "entities": ["StaffPerson", "Category", "LeaveReq", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["人员建档 → 提交请假 → 审批销假"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "人员档案", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "请假审批", "status": "flow"},
            {"name": "请假记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "人脸考勤", "status": "out_of_mvp"},
            {"name": "GPS轨迹打卡", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["人脸考勤", "GPS轨迹打卡"],
        "themes": [
            {"id": "attend-sky", "label": "假勤天蓝"},
            {"id": "attend-leaf", "label": "销假叶绿"},
            {"id": "attend-slate", "label": "台账灰青"},
            {"id": "attend-night", "label": "值班深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="人员档案",
            flow_feature="请假审批",
            records_feature="请假记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "leave_req",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "staff_person",
        },
    },
    "DOM-RECRUIT": {
        "label": "招聘投递",
        "keywords": [
            "招聘", "投递", "校招", "应聘", "简历投递", "校园招聘",
            "岗位发布", "招聘系统", "人才招聘", "网申", "职位申请",
            "招聘岗位", "双选会", "求职投递",
        ],
        "match_hint": (
            "适用：岗位发布、简历投递、初筛/录用审核。"
            "勿与客户跟进（CRM）或实习周报（实习管理）混淆。"
        ),
        "entities": ["JobPost", "Category", "JobApply", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["岗位发布 → 简历投递 → 初筛录用"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "岗位档案", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "投递审核", "status": "flow"},
            {"name": "投递记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "视频面试", "status": "out_of_mvp"},
            {"name": "ATS爬虫导入", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["视频面试", "ATS爬虫导入"],
        "themes": [
            {"id": "recruit-coral", "label": "校招珊瑚"},
            {"id": "recruit-ocean", "label": "岗位海蓝"},
            {"id": "recruit-sand", "label": "简历暖沙"},
            {"id": "recruit-night", "label": "夜招深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="岗位档案",
            flow_feature="投递审核",
            records_feature="投递记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "job_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "job_post",
        },
    },
    "DOM-GRADE": {
        "label": "教务成绩",
        "keywords": [
            "成绩", "补考", "成绩管理", "成绩查询", "成绩更正", "教务成绩",
            "成绩登记", "成绩系统", "成绩录入", "补考申请", "成绩审核",
            "缓考", "绩点查询", "成绩申请",
        ],
        "match_hint": (
            "适用：课程成绩台账、补考/成绩更正申请与教务审核。"
            "勿与选课占名额（选课）或活动报名混淆。"
        ),
        "entities": ["CourseItem", "Category", "GradeApply", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["课程建档 → 补考/更正申请 → 教务确认"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "课程档案", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "成绩申请审核", "status": "flow"},
            {"name": "成绩申请记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "学信网对接", "status": "out_of_mvp"},
            {"name": "复杂绩点引擎", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["学信网对接", "复杂绩点引擎"],
        "themes": [
            {"id": "grade-ink", "label": "教务墨蓝"},
            {"id": "grade-leaf", "label": "成绩青绿"},
            {"id": "grade-amber", "label": "补考琥珀"},
            {"id": "grade-night", "label": "夜查深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="课程档案",
            flow_feature="成绩申请审核",
            records_feature="成绩申请记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "grade_apply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "course_item",
        },
    },
    "DOM-INTERN": {
        "label": "实习周报",
        "keywords": [
            "实习", "周报", "实习周报", "实习管理", "实习鉴定", "实习岗位",
            "学生实习", "顶岗实习", "实习系统", "实习导师", "实习单位",
            "实习报告", "校外实习", "实习考勤",
        ],
        "match_hint": (
            "适用：实习岗位建档、周报提交与导师审阅。"
            "勿与活动报名或招聘投递（仅投简历）混淆。"
        ),
        "entities": ["InternPost", "Category", "WeekReport", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["实习岗建档 → 提交周报 → 导师审阅"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "实习岗位", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "周报审阅", "status": "flow"},
            {"name": "周报记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "三方协议电子签", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["三方协议电子签"],
        "themes": [
            {"id": "intern-teal", "label": "实习青绿"},
            {"id": "intern-sand", "label": "周报暖沙"},
            {"id": "intern-slate", "label": "鉴定灰青"},
            {"id": "intern-night", "label": "夜写深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="实习岗位",
            flow_feature="周报审阅",
            records_feature="周报记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "week_report",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "intern_post",
        },
    },
    "DOM-PARCEL": {
        "label": "快递驿站",
        "keywords": [
            "快递", "驿站", "取件", "包裹", "快递驿站", "校园快递",
            "取件码", "快递代收", "驿站管理", "包裹取件", "代收点",
            "快递入库", "快递领取", "催取",
        ],
        "match_hint": (
            "适用：包裹入库、取件码核销、驿站取件申请。"
            "勿与失物招领（遗失物品）混淆；智能柜硬件对接不在本期。"
        ),
        "entities": ["Parcel", "Category", "ParcelClaim", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["包裹入库 → 取件申请 → 核销出库"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "包裹台账", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "取件核销", "status": "flow"},
            {"name": "取件记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "智能柜硬件对接", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["智能柜硬件对接"],
        "themes": [
            {"id": "parcel-orange", "label": "包裹橙"},
            {"id": "parcel-sky", "label": "驿站天蓝"},
            {"id": "parcel-slate", "label": "柜号灰青"},
            {"id": "parcel-night", "label": "夜取深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="包裹台账",
            flow_feature="取件核销",
            records_feature="取件记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "parcel_claim",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "parcel",
        },
    },
    "DOM-SHOP": {
        "label": "商城",
        "keywords": ["商城", "商品", "购物车", "下单", "电商", "网购", "二手"],
        "match_hint": "适用：商品浏览、购物车下单交易。勿与点餐（食堂菜品）或客房预订混淆。",
        "entities": ["Product", "Category", "Order", "Cart", "Guestbook", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["加购 → 下单 → 发货"],
        "features": [
            {"name": "用户登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "商品浏览", "status": "domain"},
            {"name": "购物车下单", "status": "flow"},
            {"name": "订单管理", "status": "flow"},
            {"name": "用户管理", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "访客留言", "status": "module"},
            {"name": "推荐算法", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["推荐算法"],
        "themes": [
            {"id": "shop-coral", "label": "促销珊瑚"},
            {"id": "shop-ocean", "label": "清仓海蓝"},
            {"id": "shop-lime", "label": "生鲜青绿"},
            {"id": "shop-gold", "label": "会员金"},
            {"id": "shop-night", "label": "夜间闪购"},
        ],
        "gate": gate_order_shell(
            archive_feature="商品浏览",
            cart_feature="购物车下单",
            orders_feature="订单管理",
        ),
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "product",
            "order_cart_table": "cart_line",
            "order_table": "biz_order",
            "order_line_table": "order_line",
            "use_quota": True,
        },
    },
    "DOM-DORM": {
        "label": "宿舍",
        # 不用光杆「报修」：仪器/物业报修会误落宿舍壳；报修行为走 ARCH-FLOW
        "keywords": [
            "宿舍",
            "寝室",
            "公寓",
            "水电",
            "宿舍报修",
            "宿舍卫生",
            "寝室卫生",
            "卫生检查",
            "卫生整改",
        ],
        "match_hint": (
            "适用：宿舍水电报修、寝室维修/卫生检查整改工单。"
            "勿与物业报修（小区）、IT 报修或传染病晨检（事件上报）混淆。"
        ),
        "entities": ["Dorm", "Repair", "Notice"],
        "roles": ["student", "admin", "subadmin"],
        "flows": ["提交报修 → 受理 → 完成"],
        "features": [
            {"name": "学生登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "楼栋房间管理", "status": "module"},
            {"name": "报修类型管理", "status": "module"},
            {"name": "学生管理", "status": "module"},
            {"name": "报修申请 → 受理", "status": "flow"},
            {"name": "报修记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "人脸门禁", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["人脸门禁"],
        "themes": [
            {"id": "dorm-sky", "label": "宿舍天蓝"},
            {"id": "dorm-orange", "label": "维修橙"},
            {"id": "dorm-leaf", "label": "生活绿"},
            {"id": "dorm-violet", "label": "寝室紫雾"},
            {"id": "dorm-night", "label": "熄灯模式"},
        ],
        "gate": gate_standalone_ticket(
            flow_feature="报修申请 → 受理",
            records_feature="报修记录",
            users_feature="学生管理",
            site_feature="楼栋房间管理",
            type_feature="报修类型管理",
        ),
        "runtime": {
            "ticket_mode": "standalone",
            "ticket_table": "repair",
            "register_role": "student",
            "lookup_site_table": "dorm_building",
            "lookup_unit_table": "dorm_room",
            "lookup_type_table": "repair_type",
            "lookup_site_label": "楼栋",
            "lookup_unit_label": "房间",
            "lookup_type_label": "报修类型",
        },
    },
    "DOM-PROPERTY": {
        "label": "物业报修",
        "keywords": ["物业", "社区报修", "维修工单", "小区报修"],
        "match_hint": "适用：物业/社区/小区报修工单。勿与宿舍报修或 IT 报修混淆。",
        "entities": ["Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["提交报修 → 受理 → 完成"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "楼栋房间管理", "status": "module"},
            {"name": "报修类型管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "报修申请 → 受理", "status": "flow"},
            {"name": "报修记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "prop-teal", "label": "物业青绿"},
            {"id": "prop-sand", "label": "社区暖沙"},
            {"id": "prop-ink", "label": "工单墨蓝"},
            {"id": "prop-night", "label": "夜间值班"},
        ],
        "gate": gate_standalone_ticket(
            flow_feature="报修申请 → 受理",
            records_feature="报修记录",
            users_feature="用户管理",
            site_feature="楼栋房间管理",
            type_feature="报修类型管理",
        ),
        "runtime": {
            "ticket_mode": "standalone",
            "ticket_table": "ticket",
            "register_role": "user",
            "lookup_site_table": "building",
            "lookup_unit_table": "room",
            "lookup_type_table": "ticket_type",
            "lookup_site_label": "楼栋",
            "lookup_unit_label": "房间",
            "lookup_type_label": "报修类型",
        },
    },
    "DOM-IT": {
        "label": "IT 报修",
        "keywords": ["校园网", "网络报修", "IT运维", "机房报修"],
        "match_hint": "适用：校园网、机房、终端故障报修。勿与宿舍/物业报修混淆。",
        "entities": ["Ticket", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["提交故障 → 受理 → 完成"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "区域终端管理", "status": "module"},
            {"name": "故障类型管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "故障报修 → 受理", "status": "flow"},
            {"name": "报修记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "it-cyan", "label": "运维青"},
            {"id": "it-violet", "label": "机房紫"},
            {"id": "it-lime", "label": "终端绿"},
            {"id": "it-night", "label": "机房夜色"},
        ],
        "gate": gate_standalone_ticket(
            flow_feature="故障报修 → 受理",
            records_feature="报修记录",
            users_feature="用户管理",
            site_feature="区域终端管理",
            type_feature="故障类型管理",
        ),
        "runtime": {
            "ticket_mode": "standalone",
            "ticket_table": "ticket",
            "register_role": "user",
            "lookup_site_table": "campus_zone",
            "lookup_unit_table": "endpoint",
            "lookup_type_table": "fault_type",
            "lookup_site_label": "区域",
            "lookup_unit_label": "终端点",
            "lookup_type_label": "故障类型",
        },
    },
    "DOM-ACTIVITY": {
        "label": "活动报名",
        "keywords": ["社团活动", "志愿活动", "志愿者", "志愿服务", "活动报名", "讲座报名", "活动管理", "报名系统"],
        "match_hint": "适用：社团/志愿/讲座等活动报名审核。勿与选课（课程学分）或场地预约混淆。",
        "entities": ["Activity", "Category", "Signup", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["浏览活动 → 报名 → 审核占名额 → 口令签到（结束未签到记爽约）"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "活动检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "报名申请 → 审核", "status": "flow"},
            {"name": "口令签到", "status": "module"},
            {"name": "结束未签到记爽约（可选登记费用，无余额体系）", "status": "module"},
            {"name": "报名记录", "status": "module"},
            {"name": "时间冲突检测", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "人脸签到", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["人脸签到"],
        "themes": [
            {"id": "act-coral", "label": "活动珊瑚"},
            {"id": "act-sky", "label": "报名天蓝"},
            {"id": "act-lime", "label": "志愿青绿"},
            {"id": "act-night", "label": "晚会夜色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="活动检索",
            flow_feature="报名申请 → 审核",
            records_feature="报名记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "signup",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "activity",
            "check_time_conflict": True,
        },
    },
    "DOM-LOST": {
        "label": "失物招领",
        "keywords": ["失物招领", "失物", "招领", "寻物", "失物管理"],
        "match_hint": "适用：失物招领、认领审核。勿与商城二手交易或事件上报混淆。",
        "entities": ["LostItem", "Category", "Claim", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["浏览启事 → 认领申请 → 审核"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "失物检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "认领申请 → 审核", "status": "flow"},
            {"name": "认领记录", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "图像识别匹配", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["图像识别匹配"],
        "themes": [
            {"id": "lost-amber", "label": "招领暖黄"},
            {"id": "lost-blue", "label": "寻物蓝"},
            {"id": "lost-gray", "label": "登记灰"},
            {"id": "lost-night", "label": "夜间公示"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="失物检索",
            flow_feature="认领申请 → 审核",
            records_feature="认领记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "claim",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "lost_item",
        },
    },
    "DOM-COURSE": {
        "label": "选课",
        "keywords": ["选课", "公选课", "课程报名", "学分", "选课系统", "课程管理"],
        "match_hint": "适用：公选课、课程选课占名额。勿与活动报名（讲座/志愿）混淆。",
        "entities": ["Course", "Category", "Enrollment", "Notice"],
        "roles": ["student", "admin", "subadmin"],
        "flows": ["浏览课程 → 选课申请 → 审核占名额"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "课程检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "学生管理", "status": "module"},
            {"name": "选课申请 → 审核", "status": "flow"},
            {"name": "选课记录", "status": "module"},
            {"name": "时间冲突检测", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "智能排课", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["智能排课"],
        "themes": [
            {"id": "course-ink", "label": "课表墨蓝"},
            {"id": "course-grove", "label": "学期青绿"},
            {"id": "course-clay", "label": "教室暖陶"},
            {"id": "course-night", "label": "夜修模式"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="课程检索",
            flow_feature="选课申请 → 审核",
            records_feature="选课记录",
            users_feature="学生管理",
            category_feature="分类管理",
            with_deadline=False,
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "enrollment",
            "register_role": "student",
            "archive_category_table": "category",
            "archive_item_table": "course",
            "check_time_conflict": True,
        },
    },
    "DOM-FOOD": {
        "label": "点餐",
        "keywords": ["点餐", "订餐", "食堂", "饭堂", "外卖", "菜品", "餐厅", "奶茶", "快餐"],
        "match_hint": "适用：点餐/订餐下单。餐饮食品安全排查、追溯上报选事件上报，不要选本域。",
        "entities": ["Dish", "Order", "Category", "Guestbook", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["选菜 → 下单 → 堂食/自取"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "菜品浏览", "status": "domain"},
            {"name": "下单取餐", "status": "flow"},
            {"name": "订单管理", "status": "flow"},
            {"name": "用户管理", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "访客留言", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "food-chili", "label": "食堂红"},
            {"id": "food-bamboo", "label": "清新竹绿"},
            {"id": "food-sesame", "label": "暖米褐"},
            {"id": "food-berry", "label": "果饮紫"},
            {"id": "food-night", "label": "夜宵档"},
        ],
        "gate": gate_order_shell(
            archive_feature="菜品浏览",
            cart_feature="下单取餐",
            orders_feature="订单管理",
        ),
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "dish",
            "order_cart_table": "cart_line",
            "order_table": "biz_order",
            "order_line_table": "order_line",
            "use_quota": True,
        },
    },
    "DOM-HOSPITAL": {
        "label": "医院",
        # 勿单列「医院」：院感/宠物医院/慢病正文易误伤；挂号语义靠下列词
        "keywords": ["挂号", "就诊", "门诊", "就医", "诊疗", "分诊"],
        "match_hint": (
            "适用：挂号预约、门诊分诊。院感防控、病患随访、隔离观察、慢病随访选事件上报，不要选本域。"
        ),
        "entities": ["Doctor", "Department", "Appointment"],
        "roles": ["patient", "admin", "subadmin"],
        "flows": ["选科室 → 挂号 → 就诊"],
        "features": [
            {"name": "患者登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "科室医生", "status": "domain"},
            {"name": "挂号预约", "status": "flow"},
            {"name": "患者管理", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "电子病历", "status": "out_of_mvp"},
            {"name": "处方开药", "status": "out_of_mvp"},
            {"name": "检验检查", "status": "out_of_mvp"},
            {"name": "排队叫号大屏", "status": "out_of_mvp"},
            {"name": "医保对接/结算", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["电子病历", "处方开药", "检验检查", "排队叫号大屏", "医保对接/结算"],
        "themes": [
            {"id": "hosp-blue", "label": "医护蓝"},
            {"id": "hosp-mint", "label": "洁净绿"},
            {"id": "hosp-coral", "label": "分诊醒目"},
            {"id": "hosp-sky", "label": "候诊淡青"},
            {"id": "hosp-night", "label": "值班深色"},
        ],
        "gate": gate_slot_shell(
            archive_feature="科室医生",
            reserve_feature="挂号预约",
            users_feature="患者管理",
        ),
        "runtime": {
            "enable_ticket": False,
            "register_role": "patient",
            "archive_category_table": "category",
            "archive_item_table": "doctor",
            "slot_table": "resource_slot",
            "reservation_table": "reservation",
            "use_quota": False,
        },
    },
    "DOM-PARKING": {
        "label": "车位",
        "keywords": ["车位", "停车", "预约车位", "泊车", "停车场", "停车管理"],
        "match_hint": "适用：停车场车位时段预约。勿与场地预约（会议室/球馆）或客房预订混淆。",
        "entities": ["ParkingLot", "Space", "Reservation"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["选车位 → 预约 → 入场"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "车位检索", "status": "domain"},
            {"name": "车位预约", "status": "flow"},
            {"name": "用户管理", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "park-asphalt", "label": "车位灰蓝"},
            {"id": "park-signal", "label": "通行绿"},
            {"id": "park-amber", "label": "警示黄"},
            {"id": "park-cyan", "label": "导航青"},
            {"id": "park-night", "label": "地库夜色"},
        ],
        "gate": gate_slot_shell(
            archive_feature="车位检索",
            reserve_feature="车位预约",
        ),
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "space",
            "slot_table": "resource_slot",
            "reservation_table": "reservation",
            "use_quota": False,
        },
    },
    "DOM-MEETING": {
        "label": "场地预约",
        # 会议室 + 校园常见场地；皮肤文案按题名在 schema 里再细化
        "keywords": [
            "会议室", "会议室预约", "会议预约",
            "琴房", "琴房预约", "排练厅", "舞蹈室",
            "体育场", "体育馆", "球馆", "羽毛球场", "篮球场", "足球场",
            "自习室", "研习室", "研讨室",
            "场地预约", "订场", "实验室预约", "实训室预约", "游泳馆",
        ],
        "match_hint": "适用：会议室、球馆、琴房、自习室等场地时段预约。勿与车位预约或服务预约（美发）混淆。",
        "entities": ["Room", "Reservation"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["选场地 → 预约 → 取消/完成"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "场地检索", "status": "domain"},
            {"name": "时段预约", "status": "flow"},
            {"name": "用户管理", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "meet-blue", "label": "会议蓝"},
            {"id": "meet-gray", "label": "洽谈灰"},
            {"id": "meet-green", "label": "空闲绿"},
            {"id": "meet-night", "label": "夜间预约"},
        ],
        "gate": gate_slot_shell(
            archive_feature="场地检索",
            reserve_feature="时段预约",
        ),
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "room",
            "slot_table": "resource_slot",
            "reservation_table": "reservation",
            "use_quota": False,
        },
    },
    "DOM-SALON": {
        "label": "服务预约",
        "keywords": ["美发", "美容", "美容院", "理发预约", "服务预约"],
        "match_hint": "适用：美发美容等服务项目时段预约。勿与场地预约（会议室/球馆）或医院挂号混淆。",
        "entities": ["Service", "Slot", "Booking"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["选服务 → 预约时段 → 到店完成"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "服务浏览", "status": "domain"},
            {"name": "服务与预约", "status": "flow"},
            {"name": "用户管理", "status": "module"},
            {"name": "公告管理", "status": "module"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "salon-rose", "label": "护理玫瑰"},
            {"id": "salon-cream", "label": "沙龙暖米"},
            {"id": "salon-ink", "label": "造型墨"},
            {"id": "salon-night", "label": "夜场预约"},
        ],
        "gate": gate_slot_shell(
            archive_feature="服务浏览",
            reserve_feature="服务与预约",
        ),
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "service",
            "slot_table": "resource_slot",
            "reservation_table": "reservation",
            "use_quota": False,
        },
    },
    "DOM-HOTEL": {
        "label": "客房",
        "keywords": ["宾馆", "客房", "酒店", "民宿", "酒店预订", "住宿预订"],
        "match_hint": "适用：酒店/民宿客房预订入住。勿与场地预约或商城交易混淆。",
        "entities": ["Room", "Booking", "Order"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["选房 → 预订 → 入住/离店"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "房型浏览", "status": "domain"},
            {"name": "预订订单", "status": "flow"},
            {"name": "用户管理", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "真支付对接", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["真支付对接"],
        "themes": [
            {"id": "hotel-gold", "label": "酒店金"},
            {"id": "hotel-navy", "label": "客房藏蓝"},
            {"id": "hotel-sand", "label": "大堂暖沙"},
            {"id": "hotel-night", "label": "夜宿深色"},
        ],
        "gate": gate_slot_shell(
            archive_feature="房型浏览",
            reserve_feature="预订订单",
            with_orders=True,
        ),
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "room_type",
            "slot_table": "resource_slot",
            "reservation_table": "reservation",
            "order_cart_table": "cart_line",
            "order_table": "biz_order",
            "order_line_table": "order_line",
            "use_quota": False,
        },
    },
    "DOM-MEDIA": {
        "label": "影视综",
        "keywords": ["影视", "电影", "电视剧", "综艺", "视频点播", "在线视频", "片库"],
        "match_hint": "适用：影视综点播、片单收藏。勿与音乐（歌曲曲库）或博客（文章 CMS）混淆。",
        "entities": ["Media", "Category", "Favorite", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["浏览片单 → 播放 → 收藏"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "片单检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "收藏 / 想看", "status": "flow"},
            {"name": "我的收藏", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "协同过滤推荐", "status": "out_of_mvp"},
            {"name": "直播与弹幕", "status": "out_of_mvp"},
            {"name": "转码 CDN", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["协同过滤推荐", "直播与弹幕", "转码 CDN"],
        "themes": [
            {"id": "media-cinema", "label": "影院午夜"},
            {"id": "media-amber", "label": "暖幕琥珀"},
            {"id": "media-teal", "label": "荧幕青绿"},
            {"id": "media-night", "label": "观影深色"},
        ],
        "gate": gate_archive_favorites(
            archive_feature="片单检索",
            favorites_feature="收藏 / 想看",
            users_feature="用户管理",
            category_feature="分类管理",
        ),
        "portal_banners": True,
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "media",
        },
    },
    "DOM-MUSIC": {
        "label": "音乐",
        "keywords": ["音乐", "歌曲", "歌单", "在线音乐", "音乐播放器", "听歌", "曲库"],
        "match_hint": "适用：在线音乐曲库、歌单收藏。勿与影视综或博客混淆。",
        "entities": ["Track", "Category", "Favorite", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["浏览曲库 → 播放 → 收藏"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "曲库检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "收藏 / 喜欢", "status": "flow"},
            {"name": "我的收藏", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "协同过滤推荐", "status": "out_of_mvp"},
            {"name": "歌词同步", "status": "out_of_mvp"},
            {"name": "真转码 CDN", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["协同过滤推荐", "歌词同步", "真转码 CDN"],
        "themes": [
            {"id": "music-vinyl", "label": "黑胶午夜"},
            {"id": "music-amber", "label": "暖光耳机"},
            {"id": "music-teal", "label": "波形青绿"},
            {"id": "music-night", "label": "夜听深色"},
        ],
        "gate": gate_archive_favorites(
            archive_feature="曲库检索",
            favorites_feature="收藏 / 喜欢",
            users_feature="用户管理",
            category_feature="分类管理",
        ),
        "portal_banners": True,
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "track",
        },
    },
    "DOM-FORUM": {
        "label": "论坛",
        "keywords": ["论坛", "BBS", "贴吧", "社区帖子", "板块", "发帖", "回帖", "楼中楼"],
        "match_hint": "适用：BBS 论坛发帖回帖审核。勿与博客（单向文章收藏）混淆。",
        "entities": ["Post", "Category", "Reply", "Tag", "Attach", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["发帖 / 浏览 → 回复 → 版主审核展示"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "帖子检索", "status": "domain"},
            {"name": "用户发帖", "status": "flow"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "回复 / 楼中楼", "status": "flow"},
            {"name": "回复记录", "status": "module"},
            {"name": "富文本编辑", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "标签与附件（库表/ER）", "status": "module"},
            {"name": "实时私信", "status": "out_of_mvp"},
            {"name": "无限深度树形嵌套引擎", "status": "out_of_mvp"},
            {"name": "富文本协同编辑", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["实时私信", "无限深度树形嵌套引擎", "富文本协同编辑"],
        "themes": [
            {"id": "forum-ink", "label": "论坛墨蓝"},
            {"id": "forum-amber", "label": "暖帖琥珀"},
            {"id": "forum-teal", "label": "版块青绿"},
            {"id": "forum-night", "label": "夜读深色"},
        ],
        "gate": gate_archive_ticket(
            archive_feature="帖子检索",
            flow_feature="回复 / 楼中楼",
            records_feature="回复记录",
            users_feature="用户管理",
            category_feature="分类管理",
            with_deadline=False,
            user_publish=True,
            publish_feature="用户发帖",
        ),
        "portal_banners": True,
        "runtime": {
            "ticket_mode": "archive",
            "ticket_table": "reply",
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "post",
            "allow_multi_ticket": True,
            "archive_tag_table": "tag",
            "archive_item_tag_table": "post_tag",
        },
    },
    "DOM-BLOG": {
        "label": "博客",
        "keywords": ["博客", "个人博客", "文章系统", "资讯发布", "CMS", "博文"],
        "match_hint": "适用：个人博客/资讯文章浏览收藏。勿与论坛（回帖互动）或影视综混淆。",
        "entities": ["Article", "Category", "Favorite", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["浏览文章 → 收藏"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "管理端工作台", "status": "module"},
            {"name": "文章检索", "status": "domain"},
            {"name": "分类管理", "status": "module"},
            {"name": "用户管理", "status": "module"},
            {"name": "收藏 / 订阅", "status": "flow"},
            {"name": "我的收藏", "status": "module"},
            {"name": "富文本编辑", "status": "module"},
            {"name": "公告管理", "status": "module"},
            {"name": "猜你喜欢", "status": "module"},
            {"name": "富文本协同编辑", "status": "out_of_mvp"},
            {"name": "多作者工作流引擎", "status": "out_of_mvp"},
            {"name": "SEO / CDN 分发", "status": "out_of_mvp"},
        ],
        "out_of_mvp": ["富文本协同编辑", "多作者工作流引擎", "SEO / CDN 分发"],
        "themes": [
            {"id": "blog-ink", "label": "博文墨蓝"},
            {"id": "blog-grove", "label": "随笔青绿"},
            {"id": "blog-clay", "label": "暖陶阅读"},
            {"id": "blog-night", "label": "夜读深色"},
        ],
        "gate": gate_archive_favorites(
            archive_feature="文章检索",
            favorites_feature="收藏 / 订阅",
            users_feature="用户管理",
            category_feature="分类管理",
        ),
        "portal_banners": True,
        "runtime": {
            "enable_ticket": False,
            "register_role": "user",
            "archive_category_table": "category",
            "archive_item_table": "article",
        },
    },
    "DOM-GENERIC": {
        "label": "通用",
        "keywords": [],
        "match_hint": "适用：无明确行业场景的纯档案 CRUD 兜底。有更贴切领域时勿选本域。",
        "entities": ["Item", "Category", "Notice"],
        "roles": ["user", "admin", "subadmin"],
        "flows": ["新增 → 编辑 → 查询"],
        "features": [
            {"name": "登录", "status": "baseline"},
            {"name": "个人资料与头像", "status": "baseline"},
            {"name": "基础 CRUD", "status": "domain"},
        ],
        "out_of_mvp": [],
        "themes": [
            {"id": "gen-ink", "label": "通用墨蓝"},
            {"id": "gen-grove", "label": "通用青绿"},
            {"id": "gen-clay", "label": "通用暖陶"},
            {"id": "gen-night", "label": "通用深色"},
        ],
    },
}

# 档案表 / 单据表 / ticket_mode 以 domain_entities 为准（覆盖上方 runtime 同名字段）
from app.bake.domain_entities import bind_runtime_tables  # noqa: E402

bind_runtime_tables(DOMAINS)
