"""学生端可见「皮肤 / 特征」：不写 DOM-* 工厂编号。"""

from __future__ import annotations

from typing import Any

# DOM → 短皮肤 id（404/500 文案桶；非工厂目录号）
_DOMAIN_FLAVOR: dict[str, str] = {
    "DOM-LIBRARY": "library",
    "DOM-EQUIP": "equipment",
    "DOM-ASSET": "asset",
    "DOM-CRM": "crm",
    "DOM-EVENT": "event",
    "DOM-ATTEND": "attend",
    "DOM-FUND": "fund",
    "DOM-LABSAFE": "labsafe",
    "DOM-RECRUIT": "recruit",
    "DOM-DATING": "dating",
    "DOM-GRADE": "grade",
    "DOM-INTERN": "intern",
    "DOM-PARCEL": "parcel",
    "DOM-SEAL": "seal",
    "DOM-FLEET": "fleet",
    "DOM-CERT": "cert",
    "DOM-PROMO": "promo",
    "DOM-FITOUT": "fitout",
    "DOM-ACAD": "acad",
    "DOM-TRIP": "trip",
    "DOM-EXPENSE": "expense",
    "DOM-CREDIT": "credit",
    "DOM-LABOR": "labor",
    "DOM-EVAL": "eval",
    "DOM-MORAL": "moral",
    "DOM-AWARD": "award",
    "DOM-BED": "bed",
    "DOM-CHECKIN": "checkin",
    "DOM-MUTUAL-TUTOR": "tutor",
    "DOM-MUTUAL-TOPIC": "topic",
    "DOM-MUTUAL-TEAM": "team",
    "DOM-VISITOR": "visitor",
    "DOM-CARPASS": "carpass",
    "DOM-LISTING": "listing",
    "DOM-PROCURE": "procure",
    "DOM-CLUB": "club",
    "DOM-PROJ": "proj",
    "DOM-ETHIC": "ethic",
    "DOM-PARTY": "party",
    "DOM-CONTRACT": "contract",
    "DOM-INSTRUMENT": "instrument",
    "DOM-EXAM": "exam",
    "DOM-SURVEY": "survey",
    "DOM-VOTE": "vote",
    "DOM-DOCLIB": "doclib",
    "DOM-CARPOOL": "carpool",
    "DOM-TOUR": "tour",
    "DOM-TIMEBANK": "timebank",
    "DOM-CINEMA": "cinema",
    "DOM-SHOP": "shop",
    "DOM-DORM": "dorm",
    "DOM-PROPERTY": "property",
    "DOM-IT": "ithelp",
    "DOM-ACTIVITY": "activity",
    "DOM-LOST": "lostfound",
    "DOM-COURSE": "course",
    "DOM-FOOD": "food",
    "DOM-HOSPITAL": "hospital",
    "DOM-PARKING": "parking",
    "DOM-MEETING": "meeting",
    "DOM-SALON": "salon",
    "DOM-HOTEL": "hotel",
    "DOM-CARRENT": "carrent",
    "DOM-MEDIA": "media",
    "DOM-MUSIC": "music",
    "DOM-FORUM": "forum",
    "DOM-BLOG": "blog",
    "DOM-GENERIC": "generic",
}

# 页面分支用布尔特征（替代 getDomain() === 'DOM-…'）
_DOMAIN_TRAITS: dict[str, dict[str, bool]] = {
    "DOM-LIBRARY": {"shelfCopy": True, "loanFine": True},
    "DOM-EQUIP": {"loanFine": True},
    "DOM-ASSET": {"pickupFlow": True},
    # followUp：跟进类表单（渠道 / 下次复核），非「CRM 行业域」专属
    "DOM-CRM": {"followUp": True},
    "DOM-EVENT": {"followUp": True},
    "DOM-ATTEND": {"followUp": True},
    "DOM-FUND": {"followUp": True},
    "DOM-LABSAFE": {"followUp": True},
    "DOM-RECRUIT": {"followUp": True},
    "DOM-DATING": {"followUp": True},
    "DOM-GRADE": {"followUp": True},
    "DOM-INTERN": {"followUp": True},
    "DOM-PARCEL": {"pickupFlow": True},
    "DOM-SEAL": {"followUp": True},
    "DOM-FLEET": {"followUp": True},
    "DOM-CERT": {"followUp": True},
    "DOM-PROMO": {"followUp": True},
    "DOM-FITOUT": {"followUp": True},
    "DOM-ACAD": {"followUp": True},
    "DOM-TRIP": {"followUp": True},
    "DOM-EXPENSE": {"followUp": True},
    "DOM-CREDIT": {"followUp": True},
    "DOM-LABOR": {"followUp": True},
    "DOM-EVAL": {"followUp": True},
    "DOM-MORAL": {"followUp": True},
    "DOM-AWARD": {"followUp": True},
    "DOM-BED": {"followUp": True},
    "DOM-CHECKIN": {"followUp": True},
    "DOM-MUTUAL-TUTOR": {"followUp": True},
    "DOM-MUTUAL-TOPIC": {"followUp": True},
    "DOM-MUTUAL-TEAM": {"followUp": True},
    "DOM-VISITOR": {"followUp": True},
    "DOM-CARPASS": {"followUp": True},
    "DOM-LISTING": {"followUp": True},
    "DOM-PROCURE": {"followUp": True},
    "DOM-CLUB": {"followUp": True},
    "DOM-PROJ": {"followUp": True},
    "DOM-ETHIC": {"followUp": True},
    "DOM-PARTY": {"followUp": True},
    "DOM-CONTRACT": {"followUp": True},
    "DOM-INSTRUMENT": {"followUp": True, "loanFine": True, "slotPrimary": True},
    "DOM-EXAM": {"exam": True},
    "DOM-SURVEY": {"survey": True},
    "DOM-VOTE": {"vote": True},
    "DOM-DOCLIB": {"doclib": True},
    "DOM-CARPOOL": {"followUp": True},
    "DOM-TOUR": {"followUp": True},
    "DOM-TIMEBANK": {"followUp": True, "timebank": True},
    "DOM-CINEMA": {"seatSelect": True},
    "DOM-SHOP": {"addressBook": True, "shelfCopy": True},
    "DOM-FOOD": {"food": True, "addressBook": True, "shelfCopy": True},
    "DOM-LOST": {"pickupFlow": True},
    "DOM-PARKING": {"slotParking": True},
    "DOM-HOSPITAL": {"slotHospital": True},
    "DOM-MEETING": {"slotMeeting": True},
    "DOM-HOTEL": {"slotHotel": True},
    "DOM-CARRENT": {"slotCarrent": True},
    "DOM-SALON": {"slotSalon": True},
    "DOM-MEDIA": {"shelfCopy": True},
    "DOM-MUSIC": {"shelfCopy": True},
    "DOM-FORUM": {"shelfCopy": True},
    "DOM-BLOG": {"shelfCopy": True},
    "DOM-GENERIC": {"addressBook": True},
}


def flavor_for_domain(domain: str) -> str:
    return _DOMAIN_FLAVOR.get(domain) or "generic"


def traits_for_domain(domain: str) -> dict[str, bool]:
    base = dict(_DOMAIN_TRAITS.get(domain) or {})
    # 未声明的特征视为 false，不写入交付物（保持干净）
    return {k: v for k, v in base.items() if v}


# 登录氛围图 Unsplash 英文检索锚点（原 auth_hero._DOMAIN_QUERY）
_DOMAIN_AUTH_QUERY: dict[str, str] = {
    "DOM-LIBRARY": "university library books reading",
    "DOM-DORM": "university dormitory campus building",
    "DOM-PROPERTY": "residential apartment community property",
    "DOM-IT": "server room network operations campus it",
    "DOM-EQUIP": "laboratory equipment workshop",
    "DOM-ASSET": "warehouse inventory shelves",
    "DOM-CRM": "business meeting handshake office crm",
    "DOM-ATTEND": "office attendance leave request calendar desk",
    "DOM-FUND": "campus student financial aid scholarship application desk",
    "DOM-LABSAFE": "university laboratory safety access training badge",
    "DOM-RECRUIT": "campus job fair recruitment resume interview",
    "DOM-DATING": "dating matchmaking profile meetup community campus",
    "DOM-GRADE": "university academic transcript grades classroom",
    "DOM-INTERN": "student internship workplace mentor weekly report",
    "DOM-PARCEL": "campus parcel pickup station courier lockers",
    "DOM-SEAL": "office stamp seal approval desk",
    "DOM-FLEET": "company car fleet dispatch office",
    "DOM-CERT": "certificate letter stamp office desk",
    "DOM-PROMO": "campus banner poster approval desk",
    "DOM-FITOUT": "renovation construction permit office desk",
    "DOM-ACAD": "university academic status change office",
    "DOM-TRIP": "business trip overtime approval desk",
    "DOM-EXPENSE": "expense reimbursement finance desk",
    "DOM-CREDIT": "campus second classroom credit recognition desk",
    "DOM-LABOR": "campus labor education volunteer hours desk",
    "DOM-EVAL": "university course teaching evaluation survey desk",
    "DOM-MORAL": "campus comprehensive moral evaluation score desk",
    "DOM-AWARD": "campus competition award innovation credit desk",
    "DOM-BED": "university dormitory bed assignment room selection",
    "DOM-CHECKIN": "university dormitory night check return checkin",
    "DOM-MUTUAL-TUTOR": "campus tutor mutual selection dual choice",
    "DOM-MUTUAL-TOPIC": "campus topic mutual selection dual choice",
    "DOM-MUTUAL-TEAM": "campus team mutual selection dual choice",
    "DOM-VISITOR": "campus visitor registration temporary pass",
    "DOM-CARPASS": "campus vehicle temporary pass registration",
    "DOM-LISTING": "real estate listing showing follow up desk",
    "DOM-PROCURE": "purchase requisition procurement approval desk",
    "DOM-CLUB": "student club registration annual review desk",
    "DOM-PROJ": "student innovation project midterm review desk",
    "DOM-ETHIC": "ethics review thesis proposal materials desk",
    "DOM-PARTY": "party membership development materials desk",
    "DOM-CONTRACT": "contract registration single level approval desk",
    "DOM-INSTRUMENT": "laboratory instrument machine time reservation booking",
    "DOM-EXAM": "online exam question bank paper grading classroom",
    "DOM-SURVEY": "online survey questionnaire form feedback desk",
    "DOM-VOTE": "campus vote election candidate ballot desk",
    "DOM-DOCLIB": "document library knowledge base download desk",
    "DOM-CARPOOL": "campus carpool ride share trip match desk",
    "DOM-TOUR": "travel agency tour package signup desk itinerary",
    "DOM-TIMEBANK": "community time bank volunteer hours ledger desk",
    "DOM-CINEMA": "cinema theater seat map ticket purchase desk",
    "DOM-EVENT": "emergency response public health report clipboard",
    "DOM-ACTIVITY": "campus event students gathering",
    "DOM-LOST": "campus corridor lost and found desk",
    "DOM-COURSE": "university classroom lecture hall",
    "DOM-SHOP": "modern retail store aisle",
    "DOM-FOOD": "campus cafeteria food counter",
    "DOM-HOSPITAL": "hospital clinic corridor",
    "DOM-PARKING": "parking garage cars",
    "DOM-MEETING": "conference meeting room",
    "DOM-SALON": "salon service studio interior",
    "DOM-HOTEL": "hotel lobby interior",
    "DOM-CARRENT": "car rental agency fleet showroom",
    "DOM-MEDIA": "cinema movie theater screen audience",
    "DOM-MUSIC": "headphones music vinyl record studio",
    "DOM-FORUM": "online forum discussion community bulletin board",
    "DOM-BLOG": "writing desk laptop coffee blog journal",
    "DOM-GENERIC": "modern office workspace",
}


def auth_hero_query_for(domain: str) -> str:
    return _DOMAIN_AUTH_QUERY.get(domain) or _DOMAIN_AUTH_QUERY["DOM-GENERIC"]


def student_skin_payload(domain: str, domain_label: str) -> dict[str, Any]:
    """写入 APP_DELIVERED 的皮肤字段（无 DOM-*）。"""
    return {
        "flavor": flavor_for_domain(domain),
        "domainLabel": domain_label or "合成壳",
        "traits": traits_for_domain(domain),
    }
