/**
 * 菜单 key → 路径。
 * PortalLayout / AdminLayout / PortalHome 共用，勿再复制一份路由表。
 */

export const USER_MENU_PATHS = {
  home: '/home',
  archive: '/archive',
  my_archive: '/my-archive',
  my_tickets: '/tickets',
  peer_tickets: '/peer-tickets',
  content: '/notices',
  guestbook: '/guestbook',
  book_suggest: '/book-suggest',
  ai_assistant: '/ai-assistant',
  exam_papers: '/exam/papers',
  exam_attempts: '/exam/attempts',
  exam_practice: '/exam/practice',
  exam_rank: '/exam/rank',
  exam_wrongbook: '/exam/wrongbook',
  grade_scores_mine: '/grade/scores',
  survey_forms: '/survey/forms',
  survey_mine: '/survey/mine',
  vote_campaigns: '/vote/campaigns',
  vote_mine: '/vote/mine',
  doc_browse: '/doc/browse',
  doc_mine: '/doc/mine',
  tb_account: '/tb/account',
  tb_ledger: '/tb/ledger',
  seat_shows: '/seats/shows',
  e_sign_mine: '/e-sign',
  dm: '/dm',
  profile: '/profile',
  favorites: '/favorites',
  browse_history: '/browse-history',
  coupons: '/coupons',
  cart: '/cart',
  my_orders: '/orders',
  my_consigns: '/consigns',
  my_loss: '/loss',
  my_shots: '/shots',
  my_stay: '/stay',
  my_buybacks: '/buybacks',
  my_lessons: '/lessons',
  my_digital: '/digital',
  my_permits: '/permits',
  order_reviews: '/order-reviews',
  addresses: '/addresses',
  my_reservations: '/reservations',
  slots: '/slots',
  week_calendar: '/week',
  balance_mine: '/balance/mine',
  balance_ledger_mine: '/balance/ledger',
  occupy_mine: '/occupy/mine',
  messages: '/messages',
}

export const ADMIN_MENU_PATHS = {
  dashboard: '/admin/dashboard',
  messages: '/admin/messages',
  ticket_pending: '/admin/tickets',
  ticket_records: '/admin/ticket-records',
  users: '/admin/users',
  content: '/admin/notices',
  guestbook: '/admin/guestbook',
  item_comments: '/admin/item-comments',
  content_reports: '/admin/content-reports',
  audit_logs: '/admin/audit-logs',
  message_templates: '/admin/message-templates',
  staff_roster: '/admin/staff-roster',
  book_suggest: '/admin/book-suggest',
  equipment_dict: '/admin/equipment-dict',
  ai_knowledge: '/admin/ai-knowledge',
  exam_questions: '/admin/exam/questions',
  exam_papers: '/admin/exam/papers',
  exam_mark: '/admin/exam/mark',
  survey_forms: '/admin/survey/forms',
  survey_stats: '/admin/survey/stats',
  vote_candidates: '/admin/vote/candidates',
  vote_results: '/admin/vote/results',
  doc_files: '/admin/doc/files',
  doc_logs: '/admin/doc/logs',
  tb_accounts: '/admin/tb/accounts',
  tb_ledger_admin: '/admin/tb/ledger',
  stock_moves: '/admin/stock/moves',
  stock_ledger: '/admin/stock/ledger',
  balance_accounts: '/admin/balance/accounts',
  balance_ledger_admin: '/admin/balance/ledger',
  occupy_admin: '/admin/occupy',
  material_checklist: '/admin/material/checklist',
  lost_clues: '/admin/lost/clues',
  e_sign_admin: '/admin/e-sign',
  grade_scores_admin: '/admin/grade/scores',
  archive_logs: '/admin/archive-logs',
  lookup_site: '/admin/sites',
  lookup_type: '/admin/types',
  archive: '/admin/archive',
  category: '/admin/categories',
  deadline: '/admin/overdue',
  coupons: '/admin/coupons',
  delivery_slots: '/admin/delivery/slots',
  price_spans: '/admin/delivery/spans',
  purchase_permits: '/admin/purchase-permits',
  group_campaigns: '/admin/group-buys',
  blind_pools: '/admin/blind-boxes',
  consigns: '/admin/consigns',
  loss_claims: '/admin/loss',
  shoot_bundles: '/admin/shoot-bundles',
  shoot_files: '/admin/shoot-files',
  care_options: '/admin/care-options',
  stay_logs: '/admin/stay-logs',
  buybacks: '/admin/buybacks',
  buyback_slots: '/admin/buyback-slots',
  lesson_packs: '/admin/lesson-packs',
  lesson_uses: '/admin/lesson-uses',
  rental_inspect: '/admin/rental-inspect',
  room_board: '/admin/room-board',
  front_checkin: '/admin/front-checkin',
  front_checkout: '/admin/front-checkout',
  clean_tasks: '/admin/clean-tasks',
  digital_codes: '/admin/digital-codes',
  line_specs: '/admin/line-specs',
  orders: '/admin/orders',
  order_reviews: '/admin/order-reviews',
  reservations: '/admin/reservations',
  dm: '/admin/dm',
}

export function userMenuPath(key) {
  return USER_MENU_PATHS[key] || ''
}

export function adminMenuPath(key) {
  return ADMIN_MENU_PATHS[key] || ''
}
